//! Real, executed evidence for issue #157: a TypeScript/Wasm *calling*
//! consumer generated by
//! `semaprax::public_generic_consumer::typescript_calling`, written to a
//! standalone external package (its own `package.json`/`package-lock.json`/
//! `tsconfig.json`, no dependency on this repository's own TypeScript
//! sources), type-checked with the repository-pinned `typescript` 5.8.3
//! toolchain, and executed under real Node against a real, genuinely
//! compiled `.wasm` module (`reference_wasm_module::build`) that
//! `WebAssembly.instantiate`s for real and calls the one endpoint export
//! issue #155 names for real (`FIXTURE_ENDPOINT_EXPORT_NAME`).
//!
//! Known limitation, stated once here rather than hidden in prose (see
//! `typescript_calling.rs`'s own module documentation for the full
//! accounting): issue #155's Core Wasm physical adapter
//! (`public_generic_abi::wasm::provider::WasmProvider`) has never been
//! compiled to a real `.wasm` binary exposing an
//! open/input_prepare/call/result_export/release ABI. `reference_wasm_module`
//! is a TEST-ONLY fixture standing in for that missing compiled artifact; it
//! implements only the one endpoint issue #155 already documents as a real
//! Wasm export, and the generated `wasm-provider.ts`'s allocator/handle
//! registry/lifecycle bookkeeping stays host-side in TypeScript rather than
//! being delegated to real exported Wasm functions -- there are none to
//! delegate to. This harness proves the generated consumer's own real
//! execution, exact-copy-out, and exact-settlement behavior against real
//! Wasm; it does not (and cannot yet) prove a full compiled-provider
//! open/call/close ABI, because no such compiled artifact exists anywhere
//! in this repository.
//!
//! This harness is gated on `node` AND a repository-pinned `tsc` (5.8.3)
//! being available; it skips (never fails) when either is absent, matching
//! this repository's existing Node-hosted Wasm test convention
//! (`fixture.rs` in this same directory).

use std::env;
use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::{AtomicU64, Ordering};

use sha2::{Digest, Sha256};

use semaprax::public_generic_abi::boundary_profile::{
    MAX_BYTES_PER_LEAF, MAX_OWNED_LEAVES_PER_INSTANCE, MAX_TOTAL_PAYLOAD_BYTES,
};
use semaprax::public_generic_abi::carrier::{CarrierBindingV1, TargetProfile};
use semaprax::public_generic_abi::descriptor::{DescriptorV1, InstanceBinding};
use semaprax::public_generic_abi::wasm::binding::WasmProviderBindingV1;
use semaprax::public_generic_abi::wasm::provider::FIXTURE_ENDPOINT_EXPORT_NAME;
use semaprax::public_generic_consumer::rust_calling::{OwnedByteField, RecordShape};
use semaprax::public_generic_consumer::typescript_calling::{
    CallingConsumer, generate_typescript_calling_consumer,
};

use super::reference_wasm_module;

static NEXT: AtomicU64 = AtomicU64::new(0);

pub(super) fn fixture_descriptor_bytes() -> Vec<u8> {
    DescriptorV1::new("sample.transform", "transform", "sha256:1111111111111111111111111111111111111111111111111111111111111111", "sha256:2222222222222222222222222222222222222222222222222222222222222222", "sha256:3333333333333333333333333333333333333333333333333333333333333333", InstanceBinding { term: "@11:sample.pair<bytes,bool>".to_owned(), instance_digest: "sha256:4444444444444444444444444444444444444444444444444444444444444444".to_owned() }, InstanceBinding { term: "@11:sample.pair<bytes,i64>".to_owned(), instance_digest: "sha256:5555555555555555555555555555555555555555555555555555555555555555".to_owned() }).encode()
}

/// This generator's own module-artifact-identity convention, restated in
/// Rust exactly as `descriptor.ts`'s generated `computeModuleArtifactDigest`
/// restates it in TypeScript: domain-separated SHA-256 over `len(bytes) as
/// u64 little-endian || bytes`, rendered as `sha256:<hex>`. Deliberately
/// independent of `public_generic_abi::digest` (`pub(crate)`, unreachable
/// from this integration-test crate, and not the convention this generator
/// uses -- see `typescript_calling.rs`'s own module documentation).
fn module_artifact_digest(wasm_bytes: &[u8]) -> String {
    const DOMAIN: &[u8] = b"semaprax.public-generic-typescript-wasm-consumer.v1.module-artifact\0";
    let mut hasher = Sha256::new();
    hasher.update(DOMAIN);
    hasher.update((wasm_bytes.len() as u64).to_le_bytes());
    hasher.update(wasm_bytes);
    format!(
        "sha256:{:x}",
        semaprax::digest_hex::LowerHex(hasher.finalize())
    )
}

pub(super) fn fixture_binding(wasm_bytes: &[u8]) -> WasmProviderBindingV1 {
    WasmProviderBindingV1::new(
        CarrierBindingV1::new(
            "sha256:9999999999999999999999999999999999999999999999999999999999999999",
            TargetProfile::CoreWasm,
            "runtime:core-wasm-fixture-issue-157",
        ),
        module_artifact_digest(wasm_bytes),
        FIXTURE_ENDPOINT_EXPORT_NAME,
        "semaprax-0.4.1",
    )
}

fn shapes() -> (RecordShape, RecordShape) {
    let input = RecordShape::new(vec![
        OwnedByteField::new("consumers.typescript_calling.head"),
        OwnedByteField::new("consumers.typescript_calling.tail"),
    ]);
    let output = input.clone();
    (input, output)
}

/// The only generated shape that can reach the aggregate payload limit while
/// every individual leaf remains admitted.  Keep the identities distinct and
/// deterministic: their names are part of the generated field-name surface,
/// not display-only fixture text.
fn max_total_payload_shapes() -> (RecordShape, RecordShape) {
    assert_eq!(
        MAX_OWNED_LEAVES_PER_INSTANCE * MAX_BYTES_PER_LEAF,
        MAX_TOTAL_PAYLOAD_BYTES,
        "a generated caller can only saturate the total bound while all leaves remain \
         admitted when the profile's three bounds retain this exact relation"
    );
    let input = RecordShape::new(
        (0..MAX_OWNED_LEAVES_PER_INSTANCE)
            .map(|index| {
                OwnedByteField::new(format!(
                    "consumers.typescript_calling.max_total_payload.leaf.{index}"
                ))
            })
            .collect(),
    );
    let output = input.clone();
    (input, output)
}

struct Workspace(PathBuf);

impl Workspace {
    fn new(label: &str) -> Self {
        let root = env::temp_dir().join(format!(
            "spx-pg-typescript-calling-consumer-{}-{}-{label}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir_all(&root).unwrap();
        Self(root.canonicalize().unwrap())
    }

    fn path(&self, name: &str) -> PathBuf {
        self.0.join(name)
    }
}

impl Drop for Workspace {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn node_available() -> bool {
    Command::new("node")
        .arg("--version")
        .output()
        .is_ok_and(|output| output.status.success())
}

/// Locate a `tsc` matching this generator's own repository-pinned version
/// (5.8.3, the same pin `package.json`/`package-lock.json` embed --
/// matching `platform-tests/wasm-scalar-browser-v1/package.json`'s own
/// convention). Checks, in order: `SPX_PG_TSC`, `tsc` on `PATH`, and the
/// common pnpm-global install locations. Returns `None` (never panics) when
/// no matching toolchain is found, so this harness can skip rather than
/// fail on a host without it.
fn locate_tsc() -> Option<PathBuf> {
    let candidates: Vec<PathBuf> = {
        let mut list = Vec::new();
        if let Some(explicit) = env::var_os("SPX_PG_TSC") {
            list.push(PathBuf::from(explicit));
        }
        list.push(PathBuf::from("tsc"));
        if let Some(home) = env::var_os("HOME") {
            let home = PathBuf::from(home);
            list.push(home.join("Library/pnpm/tsc"));
            list.push(home.join(".local/share/pnpm/tsc"));
        }
        list
    };
    for candidate in candidates {
        let output = Command::new(&candidate).arg("--version").output();
        if let Ok(output) = output {
            if output.status.success() {
                let version = String::from_utf8_lossy(&output.stdout);
                if version.contains("5.8.3") {
                    return Some(candidate);
                }
            }
        }
    }
    None
}

fn write_generated_package(root: &Path, consumer: &CallingConsumer) {
    for (relative, contents) in consumer.files() {
        let path = root.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(&path, contents).unwrap();
    }
}

fn run(command: &mut Command, label: &str) -> Output {
    command
        .output()
        .unwrap_or_else(|error| panic!("run {label}: {error}"))
}

fn validate_wasm_script() -> &'static str {
    "import { readFileSync } from 'node:fs';\nconst bytes = readFileSync('reference.wasm');\nif (!WebAssembly.validate(bytes)) { throw new Error('reference.wasm fixture does not validate'); }\nconsole.log('reference.wasm validates');\n"
}

fn node_from(root: &Path, script: &str, artifact: Option<&str>) -> Command {
    let mut command = Command::new("node");
    command.current_dir(root).arg(script);
    if let Some(artifact) = artifact {
        command.arg(artifact);
    }
    command
}

fn count_ok_lines(stdout: &str) -> usize {
    stdout
        .lines()
        .filter(|line| line.starts_with("ok - "))
        .count()
}

fn one_byte_smaller_total_payload_budget(package_root: &Path) {
    let carrier = package_root.join("src/carrier.ts");
    let mut source = fs::read_to_string(&carrier).expect("read generated TypeScript carrier");
    const ADMITTED: &str = "export const MAX_TOTAL_PAYLOAD_BYTES = 16777216;";
    const ONE_BYTE_SHORT: &str = "export const MAX_TOTAL_PAYLOAD_BYTES = 16777215;";
    assert_eq!(
        source.matches(ADMITTED).count(),
        1,
        "the generated TypeScript total-payload budget mutation anchor drifted"
    );
    source = source.replacen(ADMITTED, ONE_BYTE_SHORT, 1);
    fs::write(carrier, source).expect("write generated TypeScript carrier mutation");
}

/// The runner deliberately discovers generated property names from the
/// generated type source rather than restating `field_name` in this harness.
/// It then creates the complete 256 x 64 KiB input shape.  In the unmutated
/// package, every byte crosses the generated input codec, real WebAssembly
/// endpoint, generated result codec and copy-out path.  In the one-byte-short
/// package, the same input must fail before endpoint execution or allocation.
fn max_total_payload_runner() -> &'static str {
    r#"
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { Provider } from "../dist/wasm-provider.js";
import { SemapraxPublicGenericException } from "../dist/errors.js";

const [wasmPath, expected] = process.argv.slice(2);
if (expected !== "accepted" && expected !== "capacity") throw new Error("expected accepted or capacity mode");
const source = readFileSync(new URL("../src/types.ts", import.meta.url), "utf8");
const inputStart = source.indexOf("export interface Input {");
const outputStart = source.indexOf("export interface Output {");
assert.ok(inputStart >= 0 && outputStart > inputStart, "generated Input/Output interfaces must remain ordered");
const fields = [...source.slice(inputStart, outputStart).matchAll(/^  readonly (field_[a-f0-9]+): Uint8Array;$/gm)].map(match => match[1]);
assert.equal(fields.length, 256, "the generated maximum shape must expose every owned field");
assert.equal(new Set(fields).size, fields.length, "generated field names must remain injective");
const input = Object.fromEntries(fields.map((field, index) => [field, new Uint8Array(65536).fill(index)]));
const provider = await Provider.open(readFileSync(wasmPath));
try {
  if (expected === "capacity") {
    assert.throws(
      () => provider.transform(input),
      error => error instanceof SemapraxPublicGenericException && error.detail.kind === "capacity-exceeded",
      "one byte below the aggregate budget must refuse the otherwise-admitted payload",
    );
    const snapshot = Provider.diagnostics.snapshot(provider);
    assert.equal(snapshot.endpoint_calls, 0, "aggregate input refusal must precede endpoint dispatch");
    assert.equal(snapshot.live_allocations, 0, "aggregate input refusal must leave no allocation");
    assert.equal(snapshot.live_handles, 0, "aggregate input refusal must leave no handle");
    console.log("MAX_TOTAL_PAYLOAD CAPACITY");
  } else {
    const output = provider.transform(input);
    for (const [index, field] of fields.entries()) {
      const leaf = output[field];
      assert.ok(leaf instanceof Uint8Array, `${field}: output leaf must be bytes`);
      assert.equal(leaf.length, 65536, `${field}: output leaf length`);
      assert.equal(leaf[0], index, `${field}: reversed uniform first byte`);
      assert.equal(leaf[leaf.length - 1], index, `${field}: reversed uniform final byte`);
    }
    const snapshot = Provider.diagnostics.snapshot(provider);
    assert.equal(snapshot.endpoint_calls, 256, "every maximum-shape leaf must dispatch once");
    assert.equal(snapshot.live_allocations, 0, "successful maximum payload must settle its result");
    assert.equal(snapshot.live_handles, 0, "successful maximum payload must settle its handles");
    console.log("MAX_TOTAL_PAYLOAD ACCEPTED");
  }
} finally {
  provider.close();
}
"#
}

fn exercise_max_total_payload_consumer(one_byte_short: bool) {
    if !node_available() {
        eprintln!("skipping: node is not available on PATH");
        return;
    }
    let Some(tsc) = locate_tsc() else {
        eprintln!("skipping: no repository-pinned (5.8.3) tsc is available on this host");
        return;
    };

    let wasm_bytes = reference_wasm_module::build();
    let (input, output) = max_total_payload_shapes();
    let binding = fixture_binding(&wasm_bytes);
    let consumer = generate_typescript_calling_consumer(
        &fixture_descriptor_bytes(),
        &binding,
        &input,
        &output,
    )
    .expect("the 256-leaf maximum shape is inside the generator's admitted bound");
    let workspace = Workspace::new(if one_byte_short {
        "max-total-payload-one-byte-short"
    } else {
        "max-total-payload"
    });
    let package_root = workspace.path("generated-typescript-consumer");
    write_generated_package(&package_root, &consumer);
    if one_byte_short {
        one_byte_smaller_total_payload_budget(&package_root);
    }
    let wasm_path = workspace.path("reference.wasm");
    fs::write(&wasm_path, wasm_bytes).expect("write reference Wasm fixture");
    let build = run(
        Command::new(&tsc)
            .current_dir(&package_root)
            .args(["-p", "tsconfig.json"]),
        "tsc -p tsconfig.json for the maximum-total-payload consumer",
    );
    assert!(
        build.status.success(),
        "the generated TypeScript maximum-total-payload consumer did not type-check:\n{}",
        String::from_utf8_lossy(&build.stderr)
    );
    fs::write(
        package_root.join("test/max-total-payload.mjs"),
        max_total_payload_runner(),
    )
    .expect("write maximum-total-payload runner");
    let expected = if one_byte_short {
        "capacity"
    } else {
        "accepted"
    };
    let execution = run(
        Command::new("node").current_dir(&package_root).args([
            "test/max-total-payload.mjs",
            "../reference.wasm",
            expected,
        ]),
        "node maximum-total-payload runner",
    );
    assert!(
        execution.status.success(),
        "the generated TypeScript maximum-total-payload consumer failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&execution.stdout),
        String::from_utf8_lossy(&execution.stderr)
    );
    let marker = if one_byte_short {
        "MAX_TOTAL_PAYLOAD CAPACITY"
    } else {
        "MAX_TOTAL_PAYLOAD ACCEPTED"
    };
    assert!(
        String::from_utf8_lossy(&execution.stdout).contains(marker),
        "maximum-total-payload runner did not emit its exact outcome marker: {marker}"
    );
}

/// Generate the TypeScript/Wasm calling consumer, type-check it as a
/// standalone external package with the repository-pinned `tsc`, and run
/// its own `test/round-trip.mjs` against a real, genuinely compiled `.wasm`
/// fixture module under real Node -- a real success round trip with exact
/// reversed-byte assertions, hostile descriptor/binding/module pairing,
/// exact-integer carrier decoding at a hostile u64::MAX leaf length and one
/// byte over the per-leaf bound, memory growth across a page boundary,
/// stale/foreign-handle rejection, and the full failure-injection ordinal
/// matrix -- each asserting zero live allocations/handles afterward.
#[test]
fn generated_typescript_calling_consumer_executes_against_a_real_wasm_module() {
    if !node_available() {
        eprintln!("skipping: node is not available on PATH");
        return;
    }
    let Some(tsc) = locate_tsc() else {
        eprintln!("skipping: no repository-pinned (5.8.3) tsc is available on this host");
        return;
    };

    let wasm_bytes = reference_wasm_module::build();
    assert_eq!(
        reference_wasm_module::ENDPOINT_EXPORT_NAME,
        FIXTURE_ENDPOINT_EXPORT_NAME,
        "the test fixture must export exactly the endpoint name issue #155 documents"
    );

    let (input, output) = shapes();
    let binding = fixture_binding(&wasm_bytes);
    let consumer = generate_typescript_calling_consumer(
        &fixture_descriptor_bytes(),
        &binding,
        &input,
        &output,
    )
    .expect("a well-formed shape must generate");

    let workspace = Workspace::new("execute");
    eprintln!(
        "generated TypeScript/Wasm calling consumer workspace: {}",
        workspace.0.display()
    );
    let package_root = workspace.path("generated-typescript-consumer");
    write_generated_package(&package_root, &consumer);
    let wasm_path = workspace.path("reference.wasm");
    fs::write(&wasm_path, &wasm_bytes).unwrap();

    // Sanity-check the hand-assembled fixture module is well-formed
    // WebAssembly per Node's own validator before trusting any test result
    // that follows -- a failure here means the fixture itself is broken,
    // not the generated consumer.
    let validate_script = workspace.path("validate.mjs");
    fs::write(&validate_script, validate_wasm_script()).unwrap();
    let validate = run(
        &mut node_from(&workspace.0, "validate.mjs", None),
        "node validate.mjs",
    );
    assert!(
        validate.status.success(),
        "the hand-assembled reference.wasm fixture failed to validate: stdout={} stderr={}",
        String::from_utf8_lossy(&validate.stdout),
        String::from_utf8_lossy(&validate.stderr)
    );

    let build_dist = run(
        Command::new(&tsc)
            .current_dir(&package_root)
            .args(["-p", "tsconfig.json"]),
        "tsc -p tsconfig.json",
    );
    assert!(
        build_dist.status.success(),
        "the generated package failed to type-check:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&build_dist.stdout),
        String::from_utf8_lossy(&build_dist.stderr)
    );
    assert!(
        package_root.join("dist/index.js").is_file(),
        "tsc must emit dist/index.js"
    );

    let round_trip = run(
        &mut node_from(
            &package_root,
            "test/round-trip.mjs",
            Some("../reference.wasm"),
        ),
        "node test/round-trip.mjs",
    );
    let stdout = String::from_utf8_lossy(&round_trip.stdout).into_owned();
    let stderr = String::from_utf8_lossy(&round_trip.stderr).into_owned();
    assert!(
        round_trip.status.success(),
        "the generated package's own round-trip tests failed:\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
    let ok_count = count_ok_lines(&stdout);
    assert_eq!(
        ok_count, 14,
        "expected exactly 14 selected 'ok - ' tests in the generated package's round trip; stdout:\n{stdout}"
    );
    assert!(
        !stdout.contains("FAIL -"),
        "no selected test may fail:\n{stdout}"
    );
}

#[test]
fn node_commands_keep_extended_windows_temp_paths_out_of_entry_arguments() {
    let workspace = Path::new(r"\\?\C:\Users\runneradmin\AppData\Local\Temp\spx");
    let validate = node_from(workspace, "validate.mjs", None);
    assert_eq!(validate.get_current_dir(), Some(workspace));
    assert_eq!(
        validate.get_args().collect::<Vec<_>>(),
        vec![OsStr::new("validate.mjs")]
    );
    let package = workspace.join("generated-typescript-consumer");
    let round_trip = node_from(&package, "test/round-trip.mjs", Some("../reference.wasm"));
    assert_eq!(round_trip.get_current_dir(), Some(package.as_path()));
    assert_eq!(
        round_trip.get_args().collect::<Vec<_>>(),
        vec![
            OsStr::new("test/round-trip.mjs"),
            OsStr::new("../reference.wasm")
        ]
    );
    assert!(validate_wasm_script().contains("readFileSync('reference.wasm')"));
}

/// The generated package depends on nothing but the pinned `typescript`
/// devDependency -- no path dependency on this repository's own TypeScript
/// sources, no runtime dependency at all.
#[test]
fn generated_package_json_declares_only_the_pinned_typescript_dev_dependency() {
    let wasm_bytes = reference_wasm_module::build();
    let (input, output) = shapes();
    let binding = fixture_binding(&wasm_bytes);
    let consumer = generate_typescript_calling_consumer(
        &fixture_descriptor_bytes(),
        &binding,
        &input,
        &output,
    )
    .expect("a well-formed shape must generate");
    let (_, package_json) = consumer
        .files()
        .iter()
        .find(|(name, _)| name == "package.json")
        .expect("package.json must be generated");
    assert!(!package_json.contains("\"dependencies\""));
    assert!(package_json.contains("\"typescript\": \"5.8.3\""));
}

/// Issue #173: the TypeScript/Wasm generated calling consumer reaches the
/// exact 16 MiB aggregate payload boundary through all 256 admitted leaves.
/// This is consumer execution over the established test-only endpoint, not a
/// claim that #229's compiled provider ABI exists.
#[test]
fn generated_typescript_consumer_executes_the_exact_maximum_total_payload() {
    exercise_max_total_payload_consumer(false);
}

/// A permanent, generated-artifact-only negative control for the positive
/// cell above.  Lowering only the consumer's own aggregate budget by one byte
/// must refuse the same 16 MiB input before either endpoint dispatch or any
/// live allocation, proving the positive path actually observes that bound.
#[test]
fn one_byte_smaller_typescript_total_budget_refuses_the_exact_maximum_payload() {
    exercise_max_total_payload_consumer(true);
}
