//! The deterministic string templates [`super::generate_rust_calling_consumer`]
//! composes. Split from `rust_calling.rs` itself only to keep that file's own
//! generator-contract logic short; every function here is a pure
//! byte-in/text-out renderer, exercised by [`super::tests`].

use std::fmt::Write as _;

use super::{RecordShape, CRATE_NAME, LIB_NAME, RUST_VERSION};

pub(super) fn cargo_toml() -> String {
    format!(
        "[package]\n\
         name = \"{CRATE_NAME}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         rust-version = \"{RUST_VERSION}\"\n\
         \n\
         [lib]\n\
         name = \"{LIB_NAME}\"\n\
         path = \"src/lib.rs\"\n\
         \n\
         [[test]]\n\
         name = \"round_trip\"\n\
         path = \"tests/round_trip.rs\"\n\
         harness = true\n\
         \n\
         [lints.rust]\n\
         unsafe_code = \"deny\"\n"
    )
}

pub(super) fn build_rs() -> String {
    BUILD_RS.to_owned()
}

const BUILD_RS: &str = r#"//! Generated by `semaprax::public_generic_consumer::rust_calling`. Links
//! this crate against the exact native provider artifact its caller
//! supplies. Never compiles or embeds provider source itself: this crate is
//! the EXTERNAL CONSUMER of issue #154's provider, not its reimplementation.
use std::env;

fn main() {
    let dir = env::var("SPX_PG_PROVIDER_LIB_DIR").expect(
        "SPX_PG_PROVIDER_LIB_DIR must name the directory holding the compiled native provider static library",
    );
    let name = env::var("SPX_PG_PROVIDER_LIB_NAME")
        .unwrap_or_else(|_| "spx_pg_reference_provider".to_owned());
    println!("cargo:rustc-link-search=native={dir}");
    println!("cargo:rustc-link-lib=static={name}");
    println!("cargo:rerun-if-env-changed=SPX_PG_PROVIDER_LIB_DIR");
    println!("cargo:rerun-if-env-changed=SPX_PG_PROVIDER_LIB_NAME");
}
"#;

pub(super) fn lib_rs() -> String {
    LIB_RS.to_owned()
}

const LIB_RS: &str = r#"//! Generated Rust *calling* consumer for one native public-generic provider
//! (issue #156). Distinct from the existing generated *metadata* consumer
//! (`semaprax::public_generic_consumer`, PG-5/PG-6's grammar half): that
//! consumer never allocates, transfers, or calls anything. This crate does:
//! `Provider::open` independently verifies an exact descriptor/provider
//! pairing before any native allocation, and `Provider::transform` consumes
//! one owned `Input` by value, transfers it across the native FFI boundary
//! exactly once, and returns an independently decoded and validated
//! `Output`.
//!
//! All `unsafe` in this crate is confined to the private `provider`
//! module (see that file's own `#![allow(unsafe_code)]`); every other
//! module denies it, and the package's own `[lints.rust] unsafe_code =
//! "deny"` (see `Cargo.toml`) enforces that for every target, including this
//! crate's own `tests/round_trip.rs`.
#![deny(unsafe_code)]

mod carrier;
mod descriptor;
pub mod error;
mod provider;
mod types;

pub use descriptor::{TRUSTED_BINDING_BYTES, TRUSTED_DESCRIPTOR_BYTES};
pub use error::Error;
pub use provider::{diagnostics, Provider};
pub use types::{Input, Output};
"#;

pub(super) fn error_rs() -> String {
    ERROR_RS.replace("\r\n", "\n")
}

const ERROR_RS: &str = include_str!("render/error_rs.txt");

pub(super) fn descriptor_rs(descriptor_bytes: &[u8], binding_bytes: &[u8]) -> String {
    let mut out = String::new();
    out.push_str(DESCRIPTOR_HEADER);
    out.push_str("pub const TRUSTED_DESCRIPTOR_BYTES: &[u8] = ");
    out.push_str(&byte_array_literal(descriptor_bytes));
    out.push_str(";\n\n");
    out.push_str("pub const TRUSTED_BINDING_BYTES: &[u8] = ");
    out.push_str(&byte_array_literal(binding_bytes));
    out.push_str(";\n\n");
    out.push_str(DESCRIPTOR_VERIFY);
    out
}

const DESCRIPTOR_HEADER: &str = r#"//! Generated by `semaprax::public_generic_consumer::rust_calling`. Embeds
//! the exact trusted descriptor and native-provider-binding bytes this
//! consumer was generated from, and this consumer's OWN independent replay
//! check -- bounded Descriptor-v1 parsing followed by an exact comparison of
//! all twelve named fields against these embedded constants -- run
//! BEFORE any native allocation. Independent of whatever replay the native
//! provider performs on its own side of the same `Provider::open` call: a
//! consumer that only trusted the native provider's answer would defeat the
//! point of an independently verified descriptor (issue #152).

use crate::error::Error;

"#;

const DESCRIPTOR_VERIFY: &str = r#"fn parse_descriptor_v1(bytes: &[u8]) -> Option<[&[u8]; 12]> {
    // The reference Descriptor v1 wire is twelve bounded UTF-8 frames. The
    // submitted bytes are never used to size an allocation or an index before
    // both the total bound and each individual frame bound are checked.
    if bytes.len() > 131_072 { return None; }
    let mut offset = 0usize;
    let mut fields = [&bytes[0..0]; 12];
    for field in 0..12usize {
        let prefix_end = offset.checked_add(8)?;
        let prefix = bytes.get(offset..prefix_end)?;
        let mut width = [0u8; 8];
        width.copy_from_slice(prefix);
        let length = usize::try_from(u64::from_le_bytes(width)).ok()?;
        if length > 65_536 { return None; }
        let end = prefix_end.checked_add(length)?;
        if end > bytes.len() { return None; }
        let content = &bytes[prefix_end..end];
        if std::str::from_utf8(content).is_err() { return None; }
        let expected = match field {
            0 => Some(b"semaprax.public-generic-descriptor.v1".as_slice()),
            1 => Some(b"semaprax.public-generic-boundary-profile.v1".as_slice()),
            2 => Some(b"semaprax.public-generic-type-grammar.v1".as_slice()),
            _ => None,
        };
        if expected.is_some_and(|version| content != version) { return None; }
        fields[field] = content;
        offset = end;
    }
    (offset == bytes.len()).then_some(fields)
}

fn descriptor_fields_replay(candidate: &[u8], trusted: &[u8]) -> bool {
    let (Some(candidate), Some(trusted)) =
        (parse_descriptor_v1(candidate), parse_descriptor_v1(trusted))
    else { return false; };
    candidate.iter().zip(trusted).all(|(actual, expected)| actual == &expected)
}

pub(crate) fn verify(descriptor_bytes: &[u8], binding_bytes: &[u8]) -> Result<(), Error> {
    if parse_descriptor_v1(descriptor_bytes).is_none() {
        return Err(Error::DescriptorRejected("submitted descriptor is not a canonical bounded Descriptor v1"));
    }
    if !descriptor_fields_replay(descriptor_bytes, TRUSTED_DESCRIPTOR_BYTES) {
        return Err(Error::DescriptorRejected(
            "submitted descriptor fields do not replay the trusted value this consumer was generated from",
        ));
    }
    if binding_bytes != TRUSTED_BINDING_BYTES {
        return Err(Error::ProviderMismatch(
            "submitted provider-binding bytes do not replay the trusted value this consumer was generated from",
        ));
    }
    Ok(())
}
"#;

pub(super) fn types_rs(input: &RecordShape, output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str(TYPES_HEADER);
    out.push_str(&record_struct("Input", input));
    out.push('\n');
    out.push_str(&record_struct("Output", output));
    out
}

const TYPES_HEADER: &str = r#"//! Generated by `semaprax::public_generic_consumer::rust_calling`. Concrete
//! owned Rust structs for this descriptor's one admitted input parameter and
//! one admitted result (see the module-level scope note in
//! `rust_calling.rs`). Field order matches descriptor order; field names are
//! derived from canonical field-identity bytes via lowercase hex (injective,
//! stable under a display-name rename), never from display text. Neither
//! struct derives `Copy` or `Clone`: an ordinary duplicate of underlying
//! carrier ownership is never available through this safe API, only a Rust
//! move.

"#;

fn record_struct(name: &str, shape: &RecordShape) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "#[derive(Debug)]");
    let _ = writeln!(out, "pub struct {name} {{");
    for field in &shape.fields {
        let _ = writeln!(out, "    /// Field identity: {:?}", field.identity);
        let _ = writeln!(out, "    pub {}: Vec<u8>,", field.field_name());
    }
    let _ = writeln!(out, "}}");
    out
}

pub(super) fn carrier_rs(input: &RecordShape, output: &RecordShape) -> String {
    let count = input.fields.len();
    let mut out = String::new();
    out.push_str(CARRIER_HEADER);
    let _ = writeln!(out, "const FIELD_COUNT: usize = {count};");
    out.push('\n');
    let body = CARRIER_BODY.replace("\r\n", "\n");
    // Keep clippy's `items_after_test_module` satisfied: the test module must
    // remain the final item in the file. `CARRIER_BODY` itself ends with
    // `mod bounded_codec_tests { ... }`; encoding helpers emitted after it
    // would trigger the lint. Splitting here preserves the exact same
    // bytes, only reordered to be lint-clean.
    let (before_tests, tests) = body
        .split_once("#[cfg(test)]")
        .map(|(head, tail)| (head, format!("#[cfg(test)]{tail}")))
        .unwrap_or((body.as_str(), String::new()));
    out.push_str(before_tests);
    out.push_str(&input_leaves_fn(input));
    out.push('\n');
    out.push_str(&output_from_leaves_fn(output));
    for (name, ty, shape) in [("input", "Input", input), ("output", "Output", output)] {
        let _ = writeln!(out, "\npub(crate) fn consume_{name}(value: {ty}) {{");
        for field in shape.fields.iter().rev() {
            let _ = writeln!(out, "    drop(value.{});", field.field_name());
        }
        out.push_str("}\n");
    }
    if !tests.is_empty() {
        out.push('\n');
        out.push_str(&tests);
        // Ensure file ends with a trailing newline, as all generated files do.
        if !out.ends_with('\n') {
            out.push('\n');
        }
    }
    out.replace("\r\n", "\n")
}

const CARRIER_HEADER: &str = r#"//! Generated by `semaprax::public_generic_consumer::rust_calling`. Codec for
//! this descriptor's flat owned-`Bytes` leaf sequence: Logical Carrier v1's
//! wire framing as the native adapter implements it -- `[u64
//! leaf_count][per leaf: u64 len][bytes]`, little-endian (see
//! `src/public_generic_abi/native/provider_body.c`'s own codec, which this
//! restates independently rather than trusts). Encoding walks fields in
//! descriptor order. Decoding independently validates leaf count and framing
//! rather than trusting the native call's own reported success -- "result is
//! decoded only after commit and independently validated."

use crate::error::Error;
use crate::types::{Input, Output};

"#;

const CARRIER_BODY: &str = include_str!("render/carrier_rs.txt");

fn input_leaves_fn(input: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("fn input_leaves(value: &Input) -> [&[u8]; FIELD_COUNT] {\n");
    out.push_str("    [\n");
    for field in &input.fields {
        let _ = writeln!(out, "        value.{}.as_slice(),", field.field_name());
    }
    out.push_str("    ]\n");
    out.push_str("}\n");
    out
}

fn output_from_leaves_fn(output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("fn output_from_leaves(leaves: Vec<Vec<u8>>) -> Result<Output, Error> {\n");
    out.push_str("    let mut leaves = leaves.into_iter();\n");
    out.push_str("    Ok(Output {\n");
    for field in &output.fields {
        let _ = writeln!(
            out,
            "        {}: leaves.next().expect(\"FIELD_COUNT leaves were already checked above\"),",
            field.field_name()
        );
    }
    out.push_str("    })\n");
    out.push_str("}\n");
    out
}

pub(super) fn provider_rs() -> String {
    // Normalized because a checkout may deliver `.txt` assets with CRLF;
    // `.gitattributes` pins them to LF, but a generator that is only
    // deterministic because of a checkout setting is not deterministic.
    // Matches `public_generic_consumer::template`'s own convention.
    PROVIDER_RS.replace("\r\n", "\n")
}

const PROVIDER_RS: &str = include_str!("render/provider_rs.txt");

pub(super) fn round_trip_rs(input: &RecordShape, output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str(ROUND_TRIP_HEADER);
    out.push_str(&sample_input_fn(input));
    out.push('\n');
    out.push_str(&input_with_first_field_fn(input));
    out.push('\n');
    out.push_str(&assert_reversed_fn(input, output));
    out.push('\n');
    out.push_str(ROUND_TRIP_BODY);
    out.push('\n');
    out.push_str(&per_leaf_bound_tests_fn(output));
    out
}

const ROUND_TRIP_HEADER: &str = r#"//! Generated by `semaprax::public_generic_consumer::rust_calling`. Real
//! execution evidence for issue #156: opens the real native provider,
//! transfers one owned input record exactly once, calls, decodes an
//! independently validated result, and proves zero live native
//! allocations/handles after every terminal case -- success, hostile
//! pairing, and every injected failure ordinal alike.

use spx_pg_rust_calling_consumer::{diagnostics, Error, Input, Output};
use spx_pg_rust_calling_consumer::{Provider, TRUSTED_BINDING_BYTES, TRUSTED_DESCRIPTOR_BYTES};

/// The per-leaf byte bound this descriptor's native provider enforces (see
/// `src/public_generic_abi/boundary_profile.rs::MAX_BYTES_PER_LEAF` and
/// `docs/PUBLIC-GENERIC-BOUNDARY-PROFILE-V1.md`). Restated here rather than
/// imported: this crate never depends on the workspace-private `semaprax`
/// crate.
const MAX_BYTES_PER_LEAF: usize = 64 * 1024;

fn reversed(bytes: &[u8]) -> Vec<u8> {
    bytes.iter().rev().copied().collect()
}

"#;

fn sample_input_fn(input: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("fn sample_input() -> Input {\n");
    out.push_str("    Input {\n");
    for (index, field) in input.fields.iter().enumerate() {
        let _ = writeln!(
            out,
            "        {}: b\"sample-{index}\".to_vec(),",
            field.field_name()
        );
    }
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

fn input_with_first_field_fn(input: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("fn input_with_first_field(bytes: Vec<u8>) -> Input {\n");
    out.push_str("    Input {\n");
    for (index, field) in input.fields.iter().enumerate() {
        if index == 0 {
            let _ = writeln!(out, "        {}: bytes,", field.field_name());
        } else {
            let _ = writeln!(out, "        {}: Vec::new(),", field.field_name());
        }
    }
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

fn assert_reversed_fn(input: &RecordShape, output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("fn assert_reversed(output: &Output, original: &Input) {\n");
    for (in_field, out_field) in input.fields.iter().zip(output.fields.iter()) {
        let _ = writeln!(
            out,
            "    assert_eq!(output.{}, reversed(&original.{}));",
            out_field.field_name(),
            in_field.field_name()
        );
    }
    out.push_str("}\n");
    out
}

const ROUND_TRIP_BODY: &str = r#"#[test]
fn success_round_trip_reverses_every_owned_leaf() {
    let mut provider =
        Provider::open(TRUSTED_DESCRIPTOR_BYTES, TRUSTED_BINDING_BYTES).expect("open");
    let input = sample_input();
    let expected = sample_input();
    let output = provider.transform(input).expect("transform");
    assert_reversed(&output, &expected);
    drop(provider);
    assert_eq!(
        diagnostics::live_allocations(),
        0,
        "zero live native allocations after a settled success"
    );
}

#[test]
fn open_rejects_a_mutated_descriptor_before_any_native_allocation() {
    let mut mutated = TRUSTED_DESCRIPTOR_BYTES.to_vec();
    mutated[0] ^= 0xff;
    let allocations_before = diagnostics::live_allocations();
    let error = Provider::open(&mutated, TRUSTED_BINDING_BYTES).unwrap_err();
    assert!(matches!(error, Error::DescriptorRejected(_)));
    assert_eq!(diagnostics::live_allocations(), allocations_before);
}

#[test]
fn open_rejects_a_mutated_binding_before_any_native_allocation() {
    let mut mutated = TRUSTED_BINDING_BYTES.to_vec();
    let last = mutated.len() - 1;
    mutated[last] ^= 0xff;
    let allocations_before = diagnostics::live_allocations();
    let error = Provider::open(TRUSTED_DESCRIPTOR_BYTES, &mutated).unwrap_err();
    assert!(matches!(error, Error::ProviderMismatch(_)));
    assert_eq!(diagnostics::live_allocations(), allocations_before);
}

#[test]
fn open_rejects_a_valid_binding_that_names_a_different_descriptor() {
    // The trusted binding is well-formed on its own, but paired against a
    // descriptor it was never generated for; this consumer's own replay (a
    // byte-exact pairing, not a semantic re-derivation) rejects it exactly
    // like a genuinely corrupted descriptor would.
    let mut different_descriptor = TRUSTED_DESCRIPTOR_BYTES.to_vec();
    different_descriptor.extend_from_slice(b"-a-different-but-well-formed-descriptor");
    let error = Provider::open(&different_descriptor, TRUSTED_BINDING_BYTES).unwrap_err();
    assert!(matches!(error, Error::DescriptorRejected(_)));
}

/// Every logical trace ordinal 0..=13 (`SPX_PG_TRACE_FRAME_VALIDATED`
/// through `SPX_PG_TRACE_CARRIER_RELEASE`; ordinal 14, the settlement call
/// itself, has nothing left to abort -- see `spx_pg_v1.h`) settles as a
/// failure with zero live native allocations/handles afterward, exactly like
/// `tests/public_generic_native_adapter_v1/probe.c`'s own C-hosted matrix
/// for the same provider.
#[test]
fn failure_injection_matrix_settles_every_ordinal_with_zero_live_resources() {
    for ordinal in 0u32..=13 {
        let mut provider =
            Provider::open(TRUSTED_DESCRIPTOR_BYTES, TRUSTED_BINDING_BYTES).expect("open");
        diagnostics::inject_failure(ordinal);
        let result = provider.transform(sample_input());
        assert!(result.is_err(), "ordinal {ordinal} must fail, got {result:?}");
        diagnostics::clear_failure_injection();
        assert_eq!(
            diagnostics::live_handles(&provider),
            0,
            "ordinal {ordinal} left a live handle on its provider"
        );
        drop(provider);
        assert_eq!(
            diagnostics::live_allocations(),
            0,
            "ordinal {ordinal} left a live native allocation"
        );
    }
}
"#;

/// The two per-leaf-bound tests: exactly at
/// `src/public_generic_abi/boundary_profile.rs::MAX_BYTES_PER_LEAF` is
/// accepted, one byte over is rejected locally by the native provider before
/// any endpoint execution. Generated (not part of the fixed
/// [`ROUND_TRIP_BODY`] template) because the assertion on the returned
/// `Output` has to name that record's actual first field.
fn per_leaf_bound_tests_fn(output: &RecordShape) -> String {
    let first_output_field = output.fields[0].field_name();
    let mut out = String::new();
    out.push_str("#[test]\n");
    out.push_str("fn exactly_the_per_leaf_byte_bound_is_accepted() {\n");
    out.push_str(
        "    let mut provider =\n        Provider::open(TRUSTED_DESCRIPTOR_BYTES, TRUSTED_BINDING_BYTES).expect(\"open\");\n",
    );
    out.push_str("    let at_bound = input_with_first_field(vec![0x5a; MAX_BYTES_PER_LEAF]);\n");
    out.push_str(
        "    let output = provider.transform(at_bound).expect(\"transform at the exact bound\");\n",
    );
    let _ = writeln!(
        out,
        "    assert_eq!(output.{first_output_field}.len(), MAX_BYTES_PER_LEAF);"
    );
    out.push_str("    drop(provider);\n");
    out.push_str("    assert_eq!(diagnostics::live_allocations(), 0);\n");
    out.push_str("}\n\n");

    out.push_str("#[test]\n");
    out.push_str("fn one_byte_over_the_per_leaf_bound_is_rejected_locally() {\n");
    out.push_str(
        "    let mut provider =\n        Provider::open(TRUSTED_DESCRIPTOR_BYTES, TRUSTED_BINDING_BYTES).expect(\"open\");\n",
    );
    out.push_str(
        "    let over_bound = input_with_first_field(vec![0x5a; MAX_BYTES_PER_LEAF + 1]);\n",
    );
    out.push_str("    let error = provider.transform(over_bound).unwrap_err();\n");
    out.push_str("    assert!(matches!(error, Error::CapacityExceeded(_)));\n");
    out.push_str("    drop(provider);\n");
    out.push_str(
        "    assert_eq!(\n        diagnostics::live_allocations(),\n        0,\n        \"a locally rejected input must leave nothing allocated\"\n    );\n",
    );
    out.push_str("}\n");
    out
}

/// One numeric byte literal per generated file, twelve bytes a line so a
/// diff of two generated crates stays readable, matching
/// `public_generic_consumer::byte_literal`'s own convention.
fn byte_array_literal(bytes: &[u8]) -> String {
    let mut out = String::from("&[\n");
    for chunk in bytes.chunks(12) {
        out.push_str("    ");
        for byte in chunk {
            let _ = write!(out, "0x{byte:02x}, ");
        }
        out.push('\n');
    }
    out.push(']');
    out
}
