//! The Kernel-0 differential test.
//!
//! For each program below (a small hand-written edge-case corpus plus
//! `super::corpus`'s deterministic generated corpus), this:
//! 1. Writes the program's `.spx` source to a temp file.
//! 2. Independently `crate::parse`s and `hir::resolve`s that same source
//!    (exactly as `super::kernel_zero.rs`'s own admission tests already do),
//!    translates the entry function via `super::reify::translate_program`,
//!    and evaluates it with `super::eval::eval_program` -- the from-scratch
//!    reference side.
//! 3. Drives the compiler's real interpreter backend through its ordinary
//!    public entry point, `crate::interpreter::interpret` (the same
//!    function `tests/interpreter_v1.rs`'s own golden-envelope tests call)
//!    -- never by constructing an `Evaluator` or calling `evaluate`/
//!    `combine` directly.
//! 4. Compares the two outcomes and, on any disagreement, records it (never
//!    panicking mid-corpus) so the full set of disagreements -- not just the
//!    first -- is visible in one test failure.
//!
//! Per this task's explicit instruction: a disagreement found here must
//! never be papered over by adjusting the reference interpreter to match
//! the compiler. If this test ever goes red, read the failure message's
//! embedded source and arguments, decide from
//! `docs/SEMANTIC-KERNEL-V1.md`/`docs/RFC-0001.md` which side is wrong, and
//! report it -- do not edit this file's comparison logic to silence it.

use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use crate::hir;
use crate::interpreter::{self, InterpreterOptions};

use super::corpus;
use super::eval::eval_program;
use super::reify::translate_program;
use super::value::{Fault, Value};

// Native C11 and Core Wasm extension of this module's own interpreter-only
// differential test -- see that submodule's header doc.
mod cross_backend;

static NEXT_ID: AtomicU64 = AtomicU64::new(0);

fn write_temp(source: &str) -> PathBuf {
    let ordinal = NEXT_ID.fetch_add(1, Ordering::Relaxed);
    let path = std::env::temp_dir().join(format!(
        "semaprax-kernel-zero-differential-{}-{ordinal}.spx",
        std::process::id()
    ));
    std::fs::write(&path, source).expect("temp corpus file must be writable");
    path
}

fn cleanup(path: &Path) {
    let _ = std::fs::remove_file(path);
}

/// One case: a whole `.spx` module, the `@id` of the function under test,
/// and the concrete argument tuples to run it with (each inner `Vec`
/// matching that function's declared parameters in order; an empty outer
/// `Vec` means "run it once with zero arguments").
struct Case {
    source: String,
    entry_id: String,
    samples: Vec<Vec<Value>>,
}

fn render_argument(value: &Value) -> String {
    match value {
        Value::Int(n) => n.to_string(),
        Value::Bool(b) => b.to_string(),
    }
}

/// The normalized shape both sides are reduced to before comparison.
#[derive(Debug, PartialEq)]
enum Outcome {
    Value(Value),
    Fault(Fault),
}

fn reference_outcome(result: Result<Value, Fault>) -> Outcome {
    match result {
        Ok(value) => Outcome::Value(value),
        Err(fault) => Outcome::Fault(fault),
    }
}

/// The exact `semaprax.arithmetic.v1` codes `StatusCase::code()` assigns
/// (`src/cleanup_plan.rs`, read-only -- confirmed against the built CLI and
/// against `tests/interpreter_v1.rs`'s own pinned
/// `"domain_id":"semaprax.arithmetic.v1","code":1` golden fragment, not
/// re-derived by calling into `src/interpreter.rs`). A status outside this
/// table can never legitimately arise from a Kernel-0 program (it has no
/// contracts, so no `semaprax.contract.v1` status is reachable either), so
/// one appearing here is itself a differential-test finding, not something
/// to translate leniently.
fn fault_from_status(domain_id: &str, code: u64) -> Option<Fault> {
    if domain_id != "semaprax.arithmetic.v1" {
        return None;
    }
    match code {
        1 => Some(Fault::AddOverflow),
        2 => Some(Fault::SubOverflow),
        3 => Some(Fault::MulOverflow),
        4 => Some(Fault::DivisionByZero),
        5 => Some(Fault::DivisionOverflow),
        6 => Some(Fault::RemainderByZero),
        7 => Some(Fault::RemainderOverflow),
        8 => Some(Fault::NegationOverflow),
        _ => None,
    }
}

fn compiler_outcome(envelope: &str, source: &str) -> Outcome {
    let json: serde_json::Value = serde_json::from_str(envelope).unwrap_or_else(|error| {
        panic!("kernel-0 differential test: envelope is not JSON: {error}\n{envelope}")
    });
    let outcome = &json["payload"]["outcome"];
    let kind = outcome["kind"].as_str().unwrap_or_else(|| {
        panic!("kernel-0 differential test: envelope has no outcome.kind\n{envelope}")
    });
    match kind {
        "returned" => {
            let value_text = outcome["value"].as_str().unwrap_or_else(|| {
                panic!("kernel-0 differential test: returned outcome has no value\n{envelope}")
            });
            match outcome["type"].as_str() {
                Some("i64") => Outcome::Value(Value::Int(value_text.parse().unwrap_or_else(|error| {
                    panic!("kernel-0 differential test: i64 outcome value {value_text:?} did not parse: {error}")
                }))),
                Some("bool") => Outcome::Value(Value::Bool(value_text == "true")),
                other => panic!(
                    "kernel-0 differential test: unexpected returned outcome type {other:?}\nsource:\n{source}"
                ),
            }
        }
        "failed" => {
            let status = &outcome["status"];
            let domain_id = status["domain_id"].as_str().unwrap_or_default();
            let code = status["code"].as_u64().unwrap_or_default();
            let fault = fault_from_status(domain_id, code).unwrap_or_else(|| {
                panic!(
                    "kernel-0 differential test: compiler failed with status domain_id={domain_id:?} \
                     code={code}, outside Kernel-0's eight arithmetic fault codes -- a Kernel-0 \
                     program has no contracts, so no other failure class should be reachable\n\
                     source:\n{source}"
                )
            });
            Outcome::Fault(fault)
        }
        other => panic!(
            "kernel-0 differential test: unexpected outcome.kind {other:?}\nsource:\n{source}"
        ),
    }
}

/// Runs one case's every sample, appending a human-readable description of
/// each disagreement to `failures` (never panicking on a mismatch itself --
/// the whole corpus keeps running so one test failure names every
/// disagreement it found, not only the first).
fn run_case(case: &Case, failures: &mut Vec<String>, total: &mut usize) {
    let path = write_temp(&case.source);
    let program =
        crate::parse(&case.source, "kernel-zero-differential.spx").unwrap_or_else(|error| {
            panic!(
                "corpus program must parse: {error:?}\nsource:\n{}",
                case.source
            )
        });
    let resolved = hir::resolve(&program).unwrap_or_else(|errors| {
        panic!(
            "corpus program must resolve: {errors:?}\nsource:\n{}",
            case.source
        )
    });
    let entry_decl = resolved
        .functions
        .iter()
        .find(|function| function.id.as_str() == case.entry_id)
        .unwrap_or_else(|| {
            panic!(
                "no resolved function named {}\nsource:\n{}",
                case.entry_id, case.source
            )
        })
        .id
        .clone();
    assert!(
        super::reifies_into_kernel_zero(&resolved, &entry_decl),
        "corpus entry {} must reify into Kernel-0 -- generator/hand-written case bug otherwise\nsource:\n{}",
        case.entry_id,
        case.source
    );
    let kernel_program = translate_program(&resolved, &entry_decl)
        .expect("just confirmed reifies_into_kernel_zero above");
    let entry_fn = kernel_program
        .function(&entry_decl)
        .expect("translate_program always includes the entry it was given");

    let samples: &[Vec<Value>] = if case.samples.is_empty() {
        &[Vec::new()]
    } else {
        &case.samples
    };
    for args in samples {
        *total += 1;
        let reference = reference_outcome(eval_program(&kernel_program, entry_fn, args));

        let argument_strings: Vec<String> = args.iter().map(render_argument).collect();
        let interpretation = interpreter::interpret(
            &path,
            &case.entry_id,
            &argument_strings,
            &InterpreterOptions::default(),
        )
        .unwrap_or_else(|diagnostics| {
            panic!(
                "compiler backend rejected a program `kernel_zero::reifies_into_kernel_zero` \
                 admitted: {diagnostics:?}\nsource:\n{}",
                case.source
            )
        });
        let compiler = compiler_outcome(&interpretation.envelope, &case.source);

        if reference != compiler {
            failures.push(format!(
                "entry {} args {args:?}:\n  reference interpreter -> {reference:?}\n  \
                 compiler interpreter  -> {compiler:?}\n  envelope: {}\n  source:\n{}",
                case.entry_id, interpretation.envelope, case.source
            ));
        }
    }
    cleanup(&path);
}

fn int_case(source: &str, entry_id: &str, samples: Vec<Vec<Value>>) -> Case {
    Case {
        source: source.to_owned(),
        entry_id: entry_id.to_owned(),
        samples,
    }
}

/// Hand-written edge cases the task calls out explicitly: overflow,
/// division/remainder by zero, short-circuit laziness, evaluation order,
/// and the documented `bool == bool`/`bool != bool` extension (see
/// `super::corpus`'s doc comment on the same gap).
fn hand_written_cases() -> Vec<Case> {
    let module = |body: &str| {
        format!(
            "module test.kernel_zero_hand_written;\n\n\
             @id(\"app.main\")\nfn main() -> i64 {{ 0 }}\n\n\
             @id(\"app.entry\")\nfn entry() -> i64\n{{\n    {body}\n}}\n"
        )
    };

    vec![
        int_case(
            &module("9223372036854775807 + 1"),
            "app.entry",
            vec![vec![]],
        ),
        int_case(
            &module("(-9223372036854775807) - 2"),
            "app.entry",
            vec![vec![]],
        ),
        int_case(
            &module("4611686018427387904 * 2"),
            "app.entry",
            vec![vec![]],
        ),
        int_case(&module("1 / 0"), "app.entry", vec![vec![]]),
        int_case(&module("1 % 0"), "app.entry", vec![vec![]]),
        int_case(
            &module("(-9223372036854775807 - 1) / -1"),
            "app.entry",
            vec![vec![]],
        ),
        int_case(
            &module("(-9223372036854775807 - 1) % -1"),
            "app.entry",
            vec![vec![]],
        ),
        int_case(
            &module("-(-9223372036854775807 - 1)"),
            "app.entry",
            vec![vec![]],
        ),
        // `if`'s untaken branch is never reduced at all -- picking the safe
        // branch must never fault, even though the other branch would.
        Case {
            source: "module test.kernel_zero_hand_written;\n\n\
                     @id(\"app.main\")\nfn main() -> i64 { 0 }\n\n\
                     @id(\"app.entry\")\nfn entry(pick: bool) -> i64\n\
                     {\n    if pick { 1 / 0 } else { 42 }\n}\n"
                .to_owned(),
            entry_id: "app.entry".to_owned(),
            samples: vec![vec![Value::Bool(false)], vec![Value::Bool(true)]],
        },
        // Lazy boolean operands execute only when required (`AGENTS.md`):
        // `false && <would-fault>` and `true || <would-fault>` must reduce
        // to a plain value, never a fault.
        Case {
            source: "module test.kernel_zero_hand_written;\n\n\
                     @id(\"app.main\")\nfn main() -> i64 { 0 }\n\n\
                     @id(\"app.entry\")\nfn entry() -> bool\n\
                     {\n    false && ((1 / 0) == 0)\n}\n"
                .to_owned(),
            entry_id: "app.entry".to_owned(),
            samples: vec![vec![]],
        },
        Case {
            source: "module test.kernel_zero_hand_written;\n\n\
                     @id(\"app.main\")\nfn main() -> i64 { 0 }\n\n\
                     @id(\"app.entry\")\nfn entry() -> bool\n\
                     {\n    true || ((1 / 0) == 0)\n}\n"
                .to_owned(),
            entry_id: "app.entry".to_owned(),
            samples: vec![vec![]],
        },
        // `bool == bool` / `bool != bool`: admitted by the real compiler and
        // by `reifies_into_kernel_zero`, not stated by the document's
        // typing table -- see the doc/report note.
        Case {
            source: "module test.kernel_zero_hand_written;\n\n\
                     @id(\"app.main\")\nfn main() -> i64 { 0 }\n\n\
                     @id(\"app.entry\")\nfn entry(a: bool, b: bool) -> bool\n\
                     {\n    a == b\n}\n"
                .to_owned(),
            entry_id: "app.entry".to_owned(),
            samples: vec![
                vec![Value::Bool(true), Value::Bool(true)],
                vec![Value::Bool(true), Value::Bool(false)],
                vec![Value::Bool(false), Value::Bool(true)],
                vec![Value::Bool(false), Value::Bool(false)],
            ],
        },
        // Non-recursive call chain, three levels deep, with a
        // non-commutative operator so left-to-right call-argument
        // evaluation is actually distinguishable from any other order.
        Case {
            source: "module test.kernel_zero_hand_written;\n\n\
                     @id(\"app.main\")\nfn main() -> i64 { 0 }\n\n\
                     @id(\"test.base\")\nfn base(a: i64, b: i64) -> i64 { a - b }\n\n\
                     @id(\"test.mid\")\nfn mid(x: i64) -> i64 { base(x, 10) }\n\n\
                     @id(\"app.entry\")\nfn entry(n: i64) -> i64\n\
                     {\n    mid(n)\n}\n"
                .to_owned(),
            entry_id: "app.entry".to_owned(),
            samples: vec![
                vec![Value::Int(0)],
                vec![Value::Int(5)],
                vec![Value::Int(100)],
            ],
        },
        // The nested `let`/`if`/call/arithmetic shape
        // `docs/SEMANTIC-KERNEL-V1.md`'s "Rung 0 evidence" section hand-ran
        // across all three backends, driven here through the real
        // differential path rather than a hand-run CLI session.
        Case {
            source: "module test.kernel_zero_hand_written;\n\n\
                     @id(\"app.main\")\nfn main() -> i64 { 0 }\n\n\
                     @id(\"test.add\")\nfn add(left: i64, right: i64) -> i64 { left + right }\n\n\
                     @id(\"test.classify\")\nfn classify(value: i64) -> i64\n\
                     {\n    if value < 0 { 0 } else { 1 }\n}\n\n\
                     @id(\"app.entry\")\nfn entry() -> i64\n\
                     {\n    let sum = add(19, 23);\n    sum + classify(42)\n}\n"
                .to_owned(),
            entry_id: "app.entry".to_owned(),
            samples: vec![vec![]],
        },
    ]
}

fn generated_cases() -> Vec<Case> {
    corpus::generated_corpus()
        .into_iter()
        .map(|program| Case {
            source: program.source,
            entry_id: program.entry_id,
            samples: program.samples,
        })
        .collect()
}

#[test]
fn reference_interpreter_agrees_with_the_compiler_over_the_kernel_zero_corpus() {
    let mut failures = Vec::new();
    let mut total = 0usize;

    let hand_written = hand_written_cases();
    let hand_written_count = hand_written.len();
    for case in &hand_written {
        run_case(case, &mut failures, &mut total);
    }

    let generated = generated_cases();
    let generated_count = generated.len();
    for case in &generated {
        run_case(case, &mut failures, &mut total);
    }

    if !failures.is_empty() {
        panic!(
            "kernel-0 differential test found {} disagreement(s) out of {total} comparisons \
             ({hand_written_count} hand-written + {generated_count} generated program(s), \
             seed {:#x}):\n\n{}",
            failures.len(),
            corpus::CORPUS_SEED,
            failures.join("\n---\n")
        );
    }
    println!(
        "kernel-0 differential test: {total} comparisons across {hand_written_count} \
         hand-written and {generated_count} generated program(s) (seed {:#x}), 0 disagreements",
        corpus::CORPUS_SEED
    );
}
