//! The Kernel-0 differential test.
//!
//! For each program below (a small hand-written edge-case corpus plus
//! `super::corpus`'s deterministic generated corpus), this:
//! 1. Writes the program's `.spx` source to a temp file.
//! 2. Independently `crate::parse`s and `hir::resolve`s that same source
//!    (exactly as `super::kernel_zero.rs`'s own admission tests already do),
//!    derives and replays `super::reify::BoundTranslation` from the exact
//!    source and entry, then evaluates the replayed term with
//!    `super::eval::eval_program` -- the from-scratch
//!    reference side.
//! 3. Drives the compiler's real interpreter backend through its ordinary
//!    public entry point, `crate::interpreter::interpret` (the same
//!    function `tests/interpreter_v1.rs`'s own golden-envelope tests call)
//!    -- never by constructing an `Evaluator` or calling `evaluate`/
//!    `combine` directly.
//! 4. Compares the two outcomes and, on any disagreement, records it (never
//!    panicking mid-corpus) so the full set of disagreements -- not just the
//!    first -- is visible in one test failure.
//!
//! Per this task's explicit instruction: a disagreement found here must
//! never be papered over by adjusting the reference interpreter to match
//! the compiler. If this test ever goes red, read the failure message's
//! embedded source and arguments, decide from
//! `docs/SEMANTIC-KERNEL-V1.md`/`docs/RFC-0001.md` which side is wrong, and
//! report it -- do not edit this file's comparison logic to silence it.

use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use crate::hir::{self, DeclarationId};
use crate::interpreter::{self, InterpreterOptions};

use super::corpus;
use super::eval::eval_program;
use super::reify::BoundTranslation;
use super::value::{Fault, Value};

// Native C11 and Core Wasm extension of this module's own interpreter-only
// differential test -- see that submodule's header doc.
mod cross_backend;

static NEXT_ID: AtomicU64 = AtomicU64::new(0);

fn write_temp(source: &str) -> PathBuf {
    let ordinal = NEXT_ID.fetch_add(1, Ordering::Relaxed);
    let path = std::env::temp_dir().join(format!(
        "semaprax-kernel-zero-differential-{}-{ordinal}.spx",
        std::process::id()
    ));
    std::fs::write(&path, source).expect("temp corpus file must be writable");
    path
}

fn cleanup(path: &Path) {
    let _ = std::fs::remove_file(path);
}

/// One case: a whole `.spx` module, the `@id` of the function under test,
/// and the concrete argument tuples to run it with (each inner `Vec`
/// matching that function's declared parameters in order; an empty outer
/// `Vec` means "run it once with zero arguments").
struct Case {
    source: String,
    entry_id: String,
    samples: Vec<Vec<Value>>,
}

fn render_argument(value: &Value) -> String {
    match value {
        Value::Int(n) => n.to_string(),
        Value::Bool(b) => b.to_string(),
    }
}

/// The normalized shape both sides are reduced to before comparison.
#[derive(Debug, PartialEq)]
enum Outcome {
    Value(Value),
    Fault(Fault),
}

fn reference_outcome(result: Result<Value, Fault>) -> Outcome {
    match result {
        Ok(value) => Outcome::Value(value),
        Err(fault) => Outcome::Fault(fault),
    }
}

/// The exact `semaprax.arithmetic.v1` codes `StatusCase::code()` assigns
/// (`src/cleanup_plan.rs`, read-only -- confirmed against the built CLI and
/// against `tests/interpreter_v1.rs`'s own pinned
/// `"domain_id":"semaprax.arithmetic.v1","code":1` golden fragment, not
/// re-derived by calling into `src/interpreter.rs`). A status outside this
/// table can never legitimately arise from a Kernel-0 program (it has no
/// contracts, so no `semaprax.contract.v1` status is reachable either), so
/// one appearing here is itself a differential-test finding, not something
/// to translate leniently.
fn fault_from_status(domain_id: &str, code: u64) -> Option<Fault> {
    if domain_id != "semaprax.arithmetic.v1" {
        return None;
    }
    match code {
        1 => Some(Fault::AddOverflow),
        2 => Some(Fault::SubOverflow),
        3 => Some(Fault::MulOverflow),
        4 => Some(Fault::DivisionByZero),
        5 => Some(Fault::DivisionOverflow),
        6 => Some(Fault::RemainderByZero),
        7 => Some(Fault::RemainderOverflow),
        8 => Some(Fault::NegationOverflow),
        _ => None,
    }
}

fn compiler_outcome(envelope: &str, source: &str) -> Outcome {
    let json: serde_json::Value = serde_json::from_str(envelope).unwrap_or_else(|error| {
        panic!("kernel-0 differential test: envelope is not JSON: {error}\n{envelope}")
    });
    let outcome = &json["payload"]["outcome"];
    let kind = outcome["kind"].as_str().unwrap_or_else(|| {
        panic!("kernel-0 differential test: envelope has no outcome.kind\n{envelope}")
    });
    match kind {
        "returned" => {
            let value_text = outcome["value"].as_str().unwrap_or_else(|| {
                panic!("kernel-0 differential test: returned outcome has no value\n{envelope}")
            });
            match outcome["type"].as_str() {
                Some("i64") => Outcome::Value(Value::Int(value_text.parse().unwrap_or_else(|error| {
                    panic!("kernel-0 differential test: i64 outcome value {value_text:?} did not parse: {error}")
                }))),
                Some("bool") => Outcome::Value(Value::Bool(value_text == "true")),
                other => panic!(
                    "kernel-0 differential test: unexpected returned outcome type {other:?}\nsource:\n{source}"
                ),
            }
        }
        "failed" => {
            let status = &outcome["status"];
            let domain_id = status["domain_id"].as_str().unwrap_or_default();
            let code = status["code"].as_u64().unwrap_or_default();
            let fault = fault_from_status(domain_id, code).unwrap_or_else(|| {
                panic!(
                    "kernel-0 differential test: compiler failed with status domain_id={domain_id:?} \
                     code={code}, outside Kernel-0's eight arithmetic fault codes -- a Kernel-0 \
                     program has no contracts, so no other failure class should be reachable\n\
                     source:\n{source}"
                )
            });
            Outcome::Fault(fault)
        }
        other => panic!(
            "kernel-0 differential test: unexpected outcome.kind {other:?}\nsource:\n{source}"
        ),
    }
}

/// Runs one case's every sample, appending a human-readable description of
/// each disagreement to `failures` (never panicking on a mismatch itself --
/// the whole corpus keeps running so one test failure names every
/// disagreement it found, not only the first).
fn run_case(case: &Case, failures: &mut Vec<String>, total: &mut usize) {
    let path = write_temp(&case.source);
    let program =
        crate::parse(&case.source, "kernel-zero-differential.spx").unwrap_or_else(|error| {
            panic!(
                "corpus program must parse: {error:?}\nsource:\n{}",
                case.source
            )
        });
    let resolved = hir::resolve(&program).unwrap_or_else(|errors| {
        panic!(
            "corpus program must resolve: {errors:?}\nsource:\n{}",
            case.source
        )
    });
    let entry_decl = resolved
        .functions
        .iter()
        .find(|function| function.id.as_str() == case.entry_id)
        .unwrap_or_else(|| {
            panic!(
                "no resolved function named {}\nsource:\n{}",
                case.entry_id, case.source
            )
        })
        .id
        .clone();
    assert!(
        super::reifies_into_kernel_zero(&resolved, &entry_decl),
        "corpus entry {} must reify into Kernel-0 -- generator/hand-written case bug otherwise\nsource:\n{}",
        case.entry_id,
        case.source
    );
    let binding = BoundTranslation::derive(&case.source, &entry_decl)
        .expect("corpus source must admit a bounded translation");
    let kernel_program = binding
        .replay(&case.source, &entry_decl)
        .expect("exact-source translation must replay before evaluation");
    let entry_fn = kernel_program
        .function(&entry_decl)
        .expect("translate_program always includes the entry it was given");

    let samples: &[Vec<Value>] = if case.samples.is_empty() {
        &[Vec::new()]
    } else {
        &case.samples
    };
    for args in samples {
        *total += 1;
        let reference = reference_outcome(eval_program(kernel_program, entry_fn, args));

        let argument_strings: Vec<String> = args.iter().map(render_argument).collect();
        let interpretation = interpreter::interpret(
            &path,
            &case.entry_id,
            &argument_strings,
            &InterpreterOptions::default(),
        )
        .unwrap_or_else(|diagnostics| {
            panic!(
                "compiler backend rejected a program `kernel_zero::reifies_into_kernel_zero` \
                 admitted: {diagnostics:?}\nsource:\n{}",
                case.source
            )
        });
        let compiler = compiler_outcome(&interpretation.envelope, &case.source);

        if reference != compiler {
            failures.push(format!(
                "entry {} args {args:?}:\n  reference interpreter -> {reference:?}\n  \
                 compiler interpreter  -> {compiler:?}\n  envelope: {}\n  source:\n{}",
                case.entry_id, interpretation.envelope, case.source
            ));
        }
    }
    cleanup(&path);
}

fn int_case(source: &str, entry_id: &str, samples: Vec<Vec<Value>>) -> Case {
    Case {
        source: source.to_owned(),
        entry_id: entry_id.to_owned(),
        samples,
    }
}

/// `depth` nested `let x{n} = x{n-1} + 1;` bindings, each a fresh, distinct
/// name (real shadowing -- rebinding an already-in-scope name -- is
/// rejected outright by the resolver with `SPX-T209`, confirmed while
/// writing this generator: an earlier draft reused one name `x` at every
/// level and the differential test's own `corpus program must resolve`
/// panic reported twenty `SPX-T209` diagnostics, one per level, showing the
/// real admitted grammar is strictly narrower than the task's own suggested
/// adversarial target here). What *is* exercised, deeply: `depth` nested
/// lexical scopes and the de-Bruijn index/shift bookkeeping each one adds --
/// an off-by-one there is far more likely to surface after many nesting
/// levels than after the generator's typical 1-2 nested `let`s (`gen_let`'s
/// `depth` budget rarely reaches this deep even by chance). Returns `depth`.
fn deep_shadow_let_chain(depth: u32) -> String {
    let mut body = format!("x{depth}");
    for level in (1..=depth).rev() {
        let prev_ref = if level == 1 {
            "0".to_owned()
        } else {
            format!("x{}", level - 1)
        };
        body = format!("{{ let x{level} = {prev_ref} + 1; {body} }}");
    }
    body
}

/// `depth` nested `if`s alternating which branch is "live" (reduces to the
/// continued computation) and which is "dead" (a `1 / 0` that must never be
/// reduced). Kernel-0's `if`'s untaken branch is never evaluated at all
/// (`AGENTS.md`'s "lazy boolean operands execute only when required" sibling
/// rule for `if`) -- the single-level hand-written case above already
/// covers this once; this stresses the same invariant at `depth` nesting so
/// a backend that only mis-evaluates a dead branch a few congruence steps
/// removed from the top (rather than at the immediate top level) still gets
/// caught. Always reduces to `1`, never faults.
fn deep_if_liveness_chain(depth: u32) -> String {
    let mut body = "1".to_owned();
    for i in 0..depth {
        body = if i % 2 == 0 {
            format!("(if true {{ {body} }} else {{ (1 / 0) }})")
        } else {
            format!("(if false {{ (1 / 0) }} else {{ {body} }})")
        };
    }
    body
}

/// Rung 1's non-trivial pure classifier. Unlike the tiny arithmetic example
/// used for rung 0, this is an independently specified decision table with
/// priority-sensitive refusals, helper calls, lazy booleans, and both `bool`
/// and `i64` inputs. Every declaration stays inside Kernel-0's scalar,
/// effect-free, acyclic fragment.
const RUNG_ONE_SOURCE: &str = r#"module test.kernel_zero_rung_one;

@id("policy.role-known")
fn role_known(role: i64) -> bool
{
    role >= 0 && role <= 3
}

@id("policy.operation-known")
fn operation_known(operation: i64) -> bool
{
    operation >= 0 && operation <= 3
}

@id("policy.write-operation")
fn write_operation(operation: i64) -> bool
{
    operation == 1 || operation == 2 || operation == 3
}

@id("policy.units-known")
fn units_known(units: i64) -> bool
{
    units >= 0 && units <= 1000
}

@id("policy.classify")
fn classify(role: i64, operation: i64, owner_match: bool, mfa: bool, suspended: bool, units: i64) -> i64
{
    if suspended { 10 } else {
        if !role_known(role) { 11 } else {
            if !operation_known(operation) { 12 } else {
                if !units_known(units) { 16 } else {
                    if operation == 0 { 0 } else {
                        if role == 0 { 13 } else {
                            if operation == 3 && (role != 3 || !mfa) { 14 } else {
                                if write_operation(operation) && !owner_match && role != 3 { 15 } else {
                                    if units > 100 && role < 2 { 17 } else { 0 }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

@id("app.main")
fn main() -> i64
{
    classify(1, 1, true, false, false, 10)
}
"#;

fn rung_one_samples() -> Vec<(Vec<Value>, i64)> {
    use Value::{Bool, Int};
    vec![
        (
            vec![
                Int(-1),
                Int(9),
                Bool(false),
                Bool(false),
                Bool(true),
                Int(-1),
            ],
            10,
        ),
        (
            vec![
                Int(-1),
                Int(0),
                Bool(true),
                Bool(false),
                Bool(false),
                Int(0),
            ],
            11,
        ),
        (
            vec![Int(1), Int(4), Bool(true), Bool(false), Bool(false), Int(0)],
            12,
        ),
        (
            vec![
                Int(1),
                Int(1),
                Bool(true),
                Bool(false),
                Bool(false),
                Int(-1),
            ],
            16,
        ),
        (
            vec![
                Int(1),
                Int(1),
                Bool(true),
                Bool(false),
                Bool(false),
                Int(1001),
            ],
            16,
        ),
        (
            vec![
                Int(0),
                Int(0),
                Bool(false),
                Bool(false),
                Bool(false),
                Int(1000),
            ],
            0,
        ),
        (
            vec![Int(0), Int(1), Bool(true), Bool(false), Bool(false), Int(1)],
            13,
        ),
        (
            vec![Int(3), Int(3), Bool(true), Bool(false), Bool(false), Int(1)],
            14,
        ),
        (
            vec![Int(2), Int(3), Bool(true), Bool(true), Bool(false), Int(1)],
            14,
        ),
        (
            vec![
                Int(1),
                Int(1),
                Bool(false),
                Bool(false),
                Bool(false),
                Int(1),
            ],
            15,
        ),
        (
            vec![
                Int(3),
                Int(2),
                Bool(false),
                Bool(false),
                Bool(false),
                Int(1),
            ],
            0,
        ),
        (
            vec![
                Int(1),
                Int(1),
                Bool(true),
                Bool(false),
                Bool(false),
                Int(101),
            ],
            17,
        ),
        (
            vec![
                Int(2),
                Int(1),
                Bool(true),
                Bool(false),
                Bool(false),
                Int(101),
            ],
            0,
        ),
        (
            vec![
                Int(1),
                Int(2),
                Bool(true),
                Bool(false),
                Bool(false),
                Int(100),
            ],
            0,
        ),
    ]
}

fn rung_one_case() -> Case {
    Case {
        source: RUNG_ONE_SOURCE.to_owned(),
        entry_id: "policy.classify".to_owned(),
        samples: rung_one_samples()
            .into_iter()
            .map(|(arguments, _)| arguments)
            .collect(),
    }
}

#[test]
fn rung_one_candidate_reifies_and_matches_reference_and_compiler_interpreters() {
    assert!(RUNG_ONE_SOURCE.len() < 4 * 1024);
    let ast = crate::parse(RUNG_ONE_SOURCE, "kernel-zero-rung-one.spx").unwrap();
    let hir = hir::resolve(&ast).unwrap();
    for id in [
        "policy.role-known",
        "policy.operation-known",
        "policy.write-operation",
        "policy.units-known",
        "policy.classify",
        "app.main",
    ] {
        assert!(
            super::reifies_into_kernel_zero(&hir, &DeclarationId::new(id)),
            "rung-1 declaration {id} left the Kernel-0 fragment"
        );
    }
    let entry = DeclarationId::new("policy.classify");
    let binding = BoundTranslation::derive(RUNG_ONE_SOURCE, &entry).unwrap();
    let program = binding.replay(RUNG_ONE_SOURCE, &entry).unwrap();
    let function = program.function(&entry).unwrap();
    let fixtures = rung_one_samples();
    assert_eq!(fixtures.len(), 14, "the decision-table corpus changed");
    for (arguments, expected) in fixtures {
        assert_eq!(
            eval_program(program, function, &arguments),
            Ok(Value::Int(expected)),
            "rung-1 decision table disagreed for {arguments:?}"
        );
    }

    let case = rung_one_case();
    let mut failures = Vec::new();
    let mut total = 0usize;
    run_case(&case, &mut failures, &mut total);
    assert_eq!(total, 14, "the focused interpreter corpus changed");
    assert!(
        failures.is_empty(),
        "rung-1 candidate disagreed with the compiler interpreter:\n{}",
        failures.join("\n---\n")
    );
}

/// Hand-written edge cases the task calls out explicitly: overflow,
/// division/remainder by zero, short-circuit laziness, evaluation order,
/// and the documented `bool == bool`/`bool != bool` extension (see
/// `super::corpus`'s doc comment on the same gap).
fn hand_written_cases() -> Vec<Case> {
    let module = |body: &str| {
        format!(
            "module test.kernel_zero_hand_written;\n\n\
             @id(\"app.main\")\nfn main() -> i64 {{ 0 }}\n\n\
             @id(\"app.entry\")\nfn entry() -> i64\n{{\n    {body}\n}}\n"
        )
    };

    let mut cases = vec![
        int_case(
            &module("9223372036854775807 + 1"),
            "app.entry",
            vec![vec![]],
        ),
        int_case(
            &module("(-9223372036854775807) - 2"),
            "app.entry",
            vec![vec![]],
        ),
        int_case(
            &module("4611686018427387904 * 2"),
            "app.entry",
            vec![vec![]],
        ),
        int_case(&module("1 / 0"), "app.entry", vec![vec![]]),
        int_case(&module("1 % 0"), "app.entry", vec![vec![]]),
        int_case(
            &module("(-9223372036854775807 - 1) / -1"),
            "app.entry",
            vec![vec![]],
        ),
        int_case(
            &module("(-9223372036854775807 - 1) % -1"),
            "app.entry",
            vec![vec![]],
        ),
        int_case(
            &module("-(-9223372036854775807 - 1)"),
            "app.entry",
            vec![vec![]],
        ),
        // `if`'s untaken branch is never reduced at all -- picking the safe
        // branch must never fault, even though the other branch would.
        Case {
            source: "module test.kernel_zero_hand_written;\n\n\
                     @id(\"app.main\")\nfn main() -> i64 { 0 }\n\n\
                     @id(\"app.entry\")\nfn entry(pick: bool) -> i64\n\
                     {\n    if pick { 1 / 0 } else { 42 }\n}\n"
                .to_owned(),
            entry_id: "app.entry".to_owned(),
            samples: vec![vec![Value::Bool(false)], vec![Value::Bool(true)]],
        },
        // Lazy boolean operands execute only when required (`AGENTS.md`):
        // `false && <would-fault>` and `true || <would-fault>` must reduce
        // to a plain value, never a fault.
        Case {
            source: "module test.kernel_zero_hand_written;\n\n\
                     @id(\"app.main\")\nfn main() -> i64 { 0 }\n\n\
                     @id(\"app.entry\")\nfn entry() -> bool\n\
                     {\n    false && ((1 / 0) == 0)\n}\n"
                .to_owned(),
            entry_id: "app.entry".to_owned(),
            samples: vec![vec![]],
        },
        Case {
            source: "module test.kernel_zero_hand_written;\n\n\
                     @id(\"app.main\")\nfn main() -> i64 { 0 }\n\n\
                     @id(\"app.entry\")\nfn entry() -> bool\n\
                     {\n    true || ((1 / 0) == 0)\n}\n"
                .to_owned(),
            entry_id: "app.entry".to_owned(),
            samples: vec![vec![]],
        },
        // `bool == bool` / `bool != bool`: admitted by the real compiler and
        // by `reifies_into_kernel_zero`, not stated by the document's
        // typing table -- see the doc/report note.
        Case {
            source: "module test.kernel_zero_hand_written;\n\n\
                     @id(\"app.main\")\nfn main() -> i64 { 0 }\n\n\
                     @id(\"app.entry\")\nfn entry(a: bool, b: bool) -> bool\n\
                     {\n    a == b\n}\n"
                .to_owned(),
            entry_id: "app.entry".to_owned(),
            samples: vec![
                vec![Value::Bool(true), Value::Bool(true)],
                vec![Value::Bool(true), Value::Bool(false)],
                vec![Value::Bool(false), Value::Bool(true)],
                vec![Value::Bool(false), Value::Bool(false)],
            ],
        },
        // Non-recursive call chain, three levels deep, with a
        // non-commutative operator so left-to-right call-argument
        // evaluation is actually distinguishable from any other order.
        Case {
            source: "module test.kernel_zero_hand_written;\n\n\
                     @id(\"app.main\")\nfn main() -> i64 { 0 }\n\n\
                     @id(\"test.base\")\nfn base(a: i64, b: i64) -> i64 { a - b }\n\n\
                     @id(\"test.mid\")\nfn mid(x: i64) -> i64 { base(x, 10) }\n\n\
                     @id(\"app.entry\")\nfn entry(n: i64) -> i64\n\
                     {\n    mid(n)\n}\n"
                .to_owned(),
            entry_id: "app.entry".to_owned(),
            samples: vec![
                vec![Value::Int(0)],
                vec![Value::Int(5)],
                vec![Value::Int(100)],
            ],
        },
        // The nested `let`/`if`/call/arithmetic shape
        // `docs/SEMANTIC-KERNEL-V1.md`'s "Rung 0 evidence" section hand-ran
        // across all three backends, driven here through the real
        // differential path rather than a hand-run CLI session.
        Case {
            source: "module test.kernel_zero_hand_written;\n\n\
                     @id(\"app.main\")\nfn main() -> i64 { 0 }\n\n\
                     @id(\"test.add\")\nfn add(left: i64, right: i64) -> i64 { left + right }\n\n\
                     @id(\"test.classify\")\nfn classify(value: i64) -> i64\n\
                     {\n    if value < 0 { 0 } else { 1 }\n}\n\n\
                     @id(\"app.entry\")\nfn entry() -> i64\n\
                     {\n    let sum = add(19, 23);\n    sum + classify(42)\n}\n"
                .to_owned(),
            entry_id: "app.entry".to_owned(),
            samples: vec![vec![]],
        },
        // Evaluation order determines *which* fault is observed when both
        // operands of a binary operator would fault: left-to-right means
        // the left operand's fault always wins, and the right operand is
        // never even reached (`eval_term`'s `let left_value = ...?;` before
        // `let right_value = ...?;`) -- not merely "a fault is produced",
        // which a right-to-left or eager-both-sides evaluator could also
        // satisfy while still disagreeing on *which* one. Each pair below
        // swaps which side faults, so a backend that got the direction
        // backwards would disagree on exactly one of the two, not both.
        int_case(&module("(1 / 0) + (5 % 0)"), "app.entry", vec![vec![]]),
        int_case(&module("(5 % 0) + (1 / 0)"), "app.entry", vec![vec![]]),
        int_case(&module("(1 / 0) - (5 % 0)"), "app.entry", vec![vec![]]),
        // Same evaluation-order requirement through a comparison operator,
        // not just `arith` -- `Cmp`'s reduction rule shares the same
        // left-to-right congruence context, per `Kernel0.lean`'s `Step`.
        Case {
            source: "module test.kernel_zero_hand_written;\n\n\
                     @id(\"app.main\")\nfn main() -> i64 { 0 }\n\n\
                     @id(\"app.entry\")\nfn entry() -> bool\n\
                     {\n    (1 / 0) < (5 % 0)\n}\n"
                .to_owned(),
            entry_id: "app.entry".to_owned(),
            samples: vec![vec![]],
        },
        // A fault in `&&`/`||`'s *left* operand must propagate regardless
        // of what the right operand is (or would be) -- distinct from the
        // `false && <would-fault>` / `true || <would-fault>` lazy-right-
        // operand cases above, which never exercise a faulting *left*
        // operand at all. Both sides here would fault differently
        // (`DivisionByZero` vs `RemainderByZero`), so the observed fault
        // also pins evaluation order, the same way the arithmetic pairs
        // above do.
        Case {
            source: "module test.kernel_zero_hand_written;\n\n\
                     @id(\"app.main\")\nfn main() -> i64 { 0 }\n\n\
                     @id(\"app.entry\")\nfn entry() -> bool\n\
                     {\n    ((1 / 0) == 0) && ((5 % 0) == 0)\n}\n"
                .to_owned(),
            entry_id: "app.entry".to_owned(),
            samples: vec![vec![]],
        },
        Case {
            source: "module test.kernel_zero_hand_written;\n\n\
                     @id(\"app.main\")\nfn main() -> i64 { 0 }\n\n\
                     @id(\"app.entry\")\nfn entry() -> bool\n\
                     {\n    ((1 / 0) == 0) || ((5 % 0) == 0)\n}\n"
                .to_owned(),
            entry_id: "app.entry".to_owned(),
            samples: vec![vec![]],
        },
        // `i64::MIN * -1`: `mul`'s own boundary overflow, distinct from the
        // `add`/`sub` boundary cases above and from `div`/`mod`'s dedicated
        // `i64::MIN`/`-1` special case -- `checked_mul` must reject `2^63`
        // (one past `i64::MAX`) the same ordinary way it rejects any other
        // out-of-range product.
        int_case(
            &module("(-9223372036854775807 - 1) * -1"),
            "app.entry",
            vec![vec![]],
        ),
        // The boundary that must *not* fault: `i64::MIN` divided or
        // remaindered by plain `1` (not `-1`) is exactly representable, and
        // `i64::MAX` remaindered by `-1` is `0`. An implementation that
        // over-applies the `i64::MIN`/`-1` special case to any negative
        // divisor, or to `div`/`mod` generically, would wrongly fault here.
        int_case(
            &module("(-9223372036854775807 - 1) / 1"),
            "app.entry",
            vec![vec![]],
        ),
        int_case(
            &module("9223372036854775807 % -1"),
            "app.entry",
            vec![vec![]],
        ),
        // A helper's parameter and the caller's own `let` binding reuse the
        // literal name `x` -- the generator's fresh `gen_vN`/`pN`/`eN` names
        // never collide, so this exact shape (which a real de-Bruijn-index
        // or naive name-based substitution bug could confuse) never arises
        // by chance. `helper`'s `x` must resolve to its own parameter, never
        // leak into or capture the caller's `x`.
        Case {
            source: "module test.kernel_zero_hand_written;\n\n\
                     @id(\"app.main\")\nfn main() -> i64 { 0 }\n\n\
                     @id(\"test.helper\")\nfn helper(x: i64) -> i64 { x + 1 }\n\n\
                     @id(\"app.entry\")\nfn entry() -> i64\n\
                     {\n    let x = 100;\n    helper(x - 90) + x\n}\n"
                .to_owned(),
            entry_id: "app.entry".to_owned(),
            samples: vec![vec![]],
        },
        // 20 nested `let`s, each a fresh distinct name one level deeper --
        // a de-Bruijn shift/substitution stress case far deeper than
        // anything the generator's own `depth` budget typically reaches.
        // See `deep_shadow_let_chain`'s own doc comment: literal shadowing
        // (reusing an in-scope name) is rejected by the resolver
        // (`SPX-T209`), confirmed while developing this case.
        int_case(
            &module(&deep_shadow_let_chain(20)),
            "app.entry",
            vec![vec![]],
        ),
        // 20 nested `if`s, alternating which branch is live, where every
        // dead branch is a `1 / 0` that must never be reduced -- the
        // single-level "untaken branch never faults" case above stressed
        // once; this stresses the same invariant at depth.
        int_case(
            &module(&deep_if_liveness_chain(20)),
            "app.entry",
            vec![vec![]],
        ),
    ];
    cases.push(rung_one_case());
    cases
}

fn generated_cases() -> Vec<Case> {
    corpus::generated_corpus()
        .into_iter()
        .chain(corpus::adversarial_fault_corpus())
        .chain(corpus::adversarial_structure_corpus())
        .map(|program| Case {
            source: program.source,
            entry_id: program.entry_id,
            samples: program.samples,
        })
        .collect()
}

#[test]
fn reference_interpreter_agrees_with_the_compiler_over_the_kernel_zero_corpus() {
    let mut failures = Vec::new();
    let mut total = 0usize;

    let hand_written = hand_written_cases();
    let hand_written_count = hand_written.len();
    for case in &hand_written {
        run_case(case, &mut failures, &mut total);
    }

    let generated = generated_cases();
    let generated_count = generated.len();
    for case in &generated {
        run_case(case, &mut failures, &mut total);
    }

    if !failures.is_empty() {
        panic!(
            "kernel-0 differential test found {} disagreement(s) out of {total} comparisons \
             ({hand_written_count} hand-written + {generated_count} generated program(s), \
             seed {:#x}):\n\n{}",
            failures.len(),
            corpus::CORPUS_SEED,
            failures.join("\n---\n")
        );
    }
    println!(
        "kernel-0 differential test: {total} comparisons across {hand_written_count} \
         hand-written and {generated_count} generated program(s) (seed {:#x}), 0 disagreements",
        corpus::CORPUS_SEED
    );
}
