//! Issue #173: an independent reference decoder and replayer for
//! [Public Generic Carrier v1](../../../docs/PUBLIC-GENERIC-CARRIER-V1.md#canonical-carrier-bytes)
//! logical carrier frames, written deliberately *without* reusing the
//! production codec in [`super::frame`].
//!
//! # Why a second decoder exists at all
//!
//! [Hostile Carrier Corpus v1](../../../docs/PUBLIC-GENERIC-CARRIER-HOSTILE-CORPUS-V1.md)
//! requires that every hostile document be refused by an implementation that
//! shares no code with the one under test. A corpus checked only against
//! [`super::frame::parse_bounded`] proves that `parse_bounded` is
//! self-consistent, not that it is correct: a defect in its framing reader,
//! its bound ordering, or its preimage assembly would be mirrored exactly by
//! a test that calls the same function.
//!
//! This module therefore restates, from the specification rather than from
//! the production source:
//!
//! * its own length-framed field reader ([`read_field`]) and 8-byte
//!   little-endian integer reader ([`read_u64`]);
//! * its own copies of the five frozen boundary bounds, cross-checked
//!   against [`crate::public_generic_abi::boundary_profile`] by
//!   [`tests::reference_bounds_equal_the_frozen_boundary_profile`] so a
//!   production bound change that is not mirrored here fails loudly instead
//!   of silently diverging;
//! * its own domain-separated preimage assembly for all three derived
//!   identities.
//!
//! # Recomputation, never trust
//!
//! The wire frame carries an `endpoint_identity_digest`, an
//! `instance_identity_digest`, a `leaf_inventory_digest` and a trailing
//! `carrier_facts_digest`. This decoder treats **none** of them as an input
//! to a decision. It recomputes:
//!
//! * `endpoint_identity_digest` from the trusted plan's `export_id`;
//! * `leaf_inventory_digest` from the trusted plan's canonical leaf-path
//!   list;
//! * `carrier_facts_digest` from the body it just parsed;
//!
//! and compares each recomputation with the submitted field. A
//! self-consistent forgery — a document whose trailing digest was correctly
//! *reminted* over mutated semantic facts, so that every internal
//! consistency check it carries succeeds — is therefore still refused,
//! because the recomputed endpoint or inventory identity no longer equals
//! the one the trusted plan derives. That is the exact failure mode issue
//! #173 names first: "a digest-only check may accept a self-consistent
//! forged document if no trusted root is recomputed."
//!
//! # What this module is not
//!
//! It performs no allocation on behalf of a hostile length claim, mints no
//! handle, transfers no ownership, invokes no endpoint, calls no host
//! function and runs no cleanup. Admitting a frame here yields plain owned
//! value bytes and nothing else; it is not authority to do any of those
//! things. It is also not a public ABI: nothing generated by the compiler
//! links against it.

use crate::public_generic_abi::boundary_profile::{
    MAX_BYTES_PER_LEAF, MAX_OWNED_LEAVES_PER_INSTANCE, MAX_TOTAL_PAYLOAD_BYTES,
};
use crate::public_generic_abi::carrier::trace::Direction;
use crate::public_generic_abi::carrier::{
    CARRIER_CAPACITY, CARRIER_REPLAY_MISMATCH, CARRIER_SCHEMA, HANDLE_GENERATION_MISMATCH,
    ILLEGAL_TRANSITION, MALFORMED_CARRIER,
};

/// The frozen carrier schema literal, restated rather than imported for the
/// identity fields this decoder validates structurally. Cross-checked
/// against [`CARRIER_SCHEMA`] in this module's tests.
pub const REFERENCE_CARRIER_SCHEMA: &str = "semaprax.public-generic-carrier.v1";

/// Domain separation for the trailing `carrier_facts_digest`.
const FRAME_DOMAIN: &[u8] = b"semaprax.public-generic-carrier.v1.frame\0";
/// Domain separation for the derived endpoint identity.
const ENDPOINT_IDENTITY_DOMAIN: &[u8] = b"semaprax.public-generic-carrier.v1.endpoint-identity\0";
/// Domain separation for the derived canonical leaf inventory.
const LEAF_INVENTORY_DOMAIN: &[u8] = b"semaprax.public-generic-carrier.v1.leaf-inventory\0";

/// This decoder's own copies of the frozen bounds. They are deliberately
/// literal rather than re-exported: see the module doc.
pub const REFERENCE_MAX_OWNED_LEAVES: u64 = 256;
/// Per-leaf payload bound, in bytes.
pub const REFERENCE_MAX_BYTES_PER_LEAF: u64 = 64 * 1024;
/// Aggregate payload bound, in bytes.
pub const REFERENCE_MAX_TOTAL_PAYLOAD_BYTES: u64 = 16 * 1024 * 1024;
/// Bound on one length-framed identity or path field, in bytes.
pub const REFERENCE_MAX_FIELD_BYTES: u64 = 64 * 1024;
/// Bound on the whole encoded document, checked before any field is read.
pub const REFERENCE_MAX_WIRE_BYTES: u64 = REFERENCE_MAX_TOTAL_PAYLOAD_BYTES + 4 * 1024 * 1024;

/// The closed, normalized public refusal class every carrier reader — the
/// production codec, this reference decoder, and the native admission guard
/// alike — collapses to. Detailed local diagnostics stay on the production
/// [`crate::diagnostic::Diagnostic`]; this is the comparable public class
/// issue #173 requires ("normalize only at the declared public error
/// boundary; preserve detailed local diagnostics separately").
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum CarrierRefusal {
    /// Framing, UTF-8, an unknown literal, an unknown variant tag, a
    /// duplicate leaf path, a declared/actual length disagreement, or
    /// trailing bytes. Stable code [`MALFORMED_CARRIER`].
    Malformed,
    /// A frozen boundary-profile bound was reached before the corresponding
    /// allocation. Stable code [`CARRIER_CAPACITY`].
    Capacity,
    /// Independent replay disagreed: a recomputed digest, a semantic
    /// binding field, the leaf inventory, or the cleanup plan. Stable code
    /// [`CARRIER_REPLAY_MISMATCH`].
    ReplayMismatch,
    /// The submitted frame is not caller-owned at the pre-transfer
    /// boundary. Stable code [`ILLEGAL_TRANSITION`].
    IllegalTransition,
    /// The submitted attempt identity is not the live one. Stable code
    /// [`HANDLE_GENERATION_MISMATCH`].
    GenerationMismatch,
}

impl CarrierRefusal {
    /// The stable diagnostic code this class publishes.
    pub fn code(self) -> &'static str {
        match self {
            Self::Malformed => MALFORMED_CARRIER,
            Self::Capacity => CARRIER_CAPACITY,
            Self::ReplayMismatch => CARRIER_REPLAY_MISMATCH,
            Self::IllegalTransition => ILLEGAL_TRANSITION,
            Self::GenerationMismatch => HANDLE_GENERATION_MISMATCH,
        }
    }

    /// Normalize a production diagnostic code into this closed class.
    /// Returns `None` for a code outside the carrier family, so a reader
    /// that refuses with an unrelated diagnostic can never be scored as
    /// agreeing with this decoder.
    pub fn from_code(code: &str) -> Option<Self> {
        Some(match code {
            MALFORMED_CARRIER => Self::Malformed,
            CARRIER_CAPACITY => Self::Capacity,
            CARRIER_REPLAY_MISMATCH => Self::ReplayMismatch,
            ILLEGAL_TRANSITION => Self::IllegalTransition,
            HANDLE_GENERATION_MISMATCH => Self::GenerationMismatch,
            _ => return None,
        })
    }
}

/// Which accountability side the submitted frame claims. Mirrors
/// [`crate::public_generic_abi::native::admission::NativeCarrierOwnership`]
/// without depending on it.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ReferenceOwnership {
    /// The caller is still accountable; the only admissible value before
    /// the physical transfer point.
    Caller,
    /// The provider has already taken accountability.
    Provider,
}

/// One admitted owned leaf. Value bytes only: no handle, no address, no
/// allocator identity, no target ownership.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ReferenceLeaf {
    /// The leaf's structural path identity.
    pub path: String,
    /// The leaf's exact payload bytes.
    pub payload: Vec<u8>,
}

/// The trusted plan a submitted document is replayed against. Every derived
/// identity is recomputed from the two trusted roots (`export_id` and the
/// canonical `leaf_paths`); none is accepted from the wire.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ReferencePlan {
    direction: Direction,
    descriptor_digest: String,
    export_id: String,
    instance_identity_digest: String,
    leaf_paths: Vec<String>,
    endpoint_identity_digest: String,
    leaf_inventory_digest: String,
}

impl ReferencePlan {
    /// Build a plan from trusted roots only.
    pub fn new(
        direction: Direction,
        descriptor_digest: impl Into<String>,
        export_id: impl Into<String>,
        instance_identity_digest: impl Into<String>,
        leaf_paths: Vec<String>,
    ) -> Self {
        let export_id = export_id.into();
        let endpoint_identity_digest = endpoint_identity_digest(&export_id);
        let leaf_inventory_digest = leaf_inventory_digest(&leaf_paths);
        Self {
            direction,
            descriptor_digest: descriptor_digest.into(),
            export_id,
            instance_identity_digest: instance_identity_digest.into(),
            leaf_paths,
            endpoint_identity_digest,
            leaf_inventory_digest,
        }
    }

    /// The direction this plan admits.
    pub fn direction(&self) -> Direction {
        self.direction
    }

    /// The trusted descriptor identity this plan is bound to.
    pub fn descriptor_digest(&self) -> &str {
        &self.descriptor_digest
    }

    /// The trusted endpoint identity, recomputed from `export_id`.
    pub fn endpoint_identity_digest(&self) -> &str {
        &self.endpoint_identity_digest
    }

    /// The trusted instance identity this plan is bound to.
    pub fn instance_identity_digest(&self) -> &str {
        &self.instance_identity_digest
    }

    /// The trusted inventory identity, recomputed from `leaf_paths`.
    pub fn leaf_inventory_digest(&self) -> &str {
        &self.leaf_inventory_digest
    }

    /// The canonical ordered leaf-path inventory.
    pub fn leaf_paths(&self) -> &[String] {
        &self.leaf_paths
    }

    /// The export identity this plan derives its endpoint identity from.
    pub fn export_id(&self) -> &str {
        &self.export_id
    }
}

/// One caller-submitted admission attempt: the envelope facts that bind a
/// single attempt, plus the untrusted document itself.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ReferenceTicket {
    /// The attempt identity the caller claims is live.
    pub generation: u64,
    /// The accountability side the caller claims.
    pub ownership: ReferenceOwnership,
    /// The settlement plan the caller claims was already checked.
    pub cleanup_plan_digest: String,
    /// The untrusted document bytes.
    pub frame_bytes: Vec<u8>,
}

/// The independent admission guard: a plan, the live attempt identity, and
/// the trusted settlement plan digest.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ReferenceAdmission {
    plan: ReferencePlan,
    generation: u64,
    cleanup_plan_digest: String,
}

impl ReferenceAdmission {
    /// Build the guard. Generation zero is reserved as an invalid attempt
    /// identity and cannot create one, exactly as the native guard requires.
    pub fn new(
        plan: ReferencePlan,
        generation: u64,
        cleanup_plan_digest: impl Into<String>,
    ) -> Result<Self, CarrierRefusal> {
        if generation == 0 {
            return Err(CarrierRefusal::Malformed);
        }
        Ok(Self {
            plan,
            generation,
            cleanup_plan_digest: cleanup_plan_digest.into(),
        })
    }

    /// The trusted plan.
    pub fn plan(&self) -> &ReferencePlan {
        &self.plan
    }

    /// The live attempt identity.
    pub fn generation(&self) -> u64 {
        self.generation
    }

    /// The trusted settlement plan digest.
    pub fn cleanup_plan_digest(&self) -> &str {
        &self.cleanup_plan_digest
    }

    /// Replay one submitted ticket. The envelope facts are checked first and
    /// cheapest-first, in the exact order the native guard uses, so the two
    /// implementations produce the same class for a document that violates
    /// more than one invariant.
    ///
    /// Returns plain owned value bytes. Nothing here allocates on a hostile
    /// length claim, mints a handle, transfers ownership, invokes an
    /// endpoint, calls a host function, or runs cleanup.
    pub fn admit(&self, ticket: &ReferenceTicket) -> Result<Vec<ReferenceLeaf>, CarrierRefusal> {
        if ticket.generation != self.generation {
            return Err(CarrierRefusal::GenerationMismatch);
        }
        if ticket.ownership != ReferenceOwnership::Caller {
            return Err(CarrierRefusal::IllegalTransition);
        }
        if ticket.cleanup_plan_digest != self.cleanup_plan_digest {
            return Err(CarrierRefusal::ReplayMismatch);
        }
        decode_and_bind(&ticket.frame_bytes, &self.plan)
    }
}

/// Length-prefix one field: an 8-byte little-endian length, then the bytes.
fn push_field(out: &mut Vec<u8>, bytes: &[u8]) {
    out.extend_from_slice(&(bytes.len() as u64).to_le_bytes());
    out.extend_from_slice(bytes);
}

/// Domain-separated SHA-256 over one preimage, rendered `sha256:<hex>`.
/// The domain, the preimage length and the preimage are all fed in, so two
/// different domains can never collide over identical bytes and a length
/// extension cannot reinterpret a boundary.
fn domain_digest(domain: &[u8], preimage: &[u8]) -> String {
    use sha2::{Digest as _, Sha256};
    let mut hash = Sha256::new();
    hash.update(domain);
    hash.update((preimage.len() as u64).to_le_bytes());
    hash.update(preimage);
    format!("sha256:{:x}", crate::digest_hex::LowerHex(hash.finalize()))
}

/// Recompute the endpoint identity from a trusted export identity. Never
/// read from the wire.
pub fn endpoint_identity_digest(export_id: &str) -> String {
    domain_digest(ENDPOINT_IDENTITY_DOMAIN, export_id.as_bytes())
}

/// Recompute the canonical leaf-inventory identity from a trusted ordered
/// path list. Count-prefixed then length-framed, so `["a", "bc"]` and
/// `["ab", "c"]` can never share a preimage. Never read from the wire.
pub fn leaf_inventory_digest(leaf_paths: &[String]) -> String {
    let mut preimage = Vec::new();
    preimage.extend_from_slice(&(leaf_paths.len() as u64).to_le_bytes());
    for path in leaf_paths {
        push_field(&mut preimage, path.as_bytes());
    }
    domain_digest(LEAF_INVENTORY_DOMAIN, &preimage)
}

/// Read one length-framed field. Refuses a truncated header, a declared
/// length over `maximum`, and a declared length running past the end of the
/// document — all three *before* the slice is taken, so a hostile length
/// claim never drives a large read.
fn read_field<'a>(
    bytes: &'a [u8],
    offset: &mut usize,
    maximum: u64,
) -> Result<&'a [u8], CarrierRefusal> {
    let header_end = offset.checked_add(8).ok_or(CarrierRefusal::Malformed)?;
    let header = bytes
        .get(*offset..header_end)
        .ok_or(CarrierRefusal::Malformed)?;
    let declared = u64::from_le_bytes(header.try_into().expect("an 8-byte slice"));
    if declared > maximum {
        return Err(CarrierRefusal::Malformed);
    }
    let declared = usize::try_from(declared).map_err(|_| CarrierRefusal::Malformed)?;
    let field_end = header_end
        .checked_add(declared)
        .ok_or(CarrierRefusal::Malformed)?;
    let field = bytes
        .get(header_end..field_end)
        .ok_or(CarrierRefusal::Malformed)?;
    *offset = field_end;
    Ok(field)
}

/// Read one length-framed UTF-8 field.
fn read_text<'a>(
    bytes: &'a [u8],
    offset: &mut usize,
    maximum: u64,
) -> Result<&'a str, CarrierRefusal> {
    let field = read_field(bytes, offset, maximum)?;
    std::str::from_utf8(field).map_err(|_| CarrierRefusal::Malformed)
}

/// Read one 8-byte little-endian integer.
fn read_u64(bytes: &[u8], offset: &mut usize) -> Result<u64, CarrierRefusal> {
    let end = offset.checked_add(8).ok_or(CarrierRefusal::Malformed)?;
    let field = bytes.get(*offset..end).ok_or(CarrierRefusal::Malformed)?;
    *offset = end;
    Ok(u64::from_le_bytes(
        field.try_into().expect("an 8-byte slice"),
    ))
}

/// Peek one 8-byte little-endian integer without consuming it, so a
/// declared per-leaf payload length can be bound-checked before the field
/// read that would otherwise act on it.
fn peek_u64(bytes: &[u8], offset: usize) -> Result<u64, CarrierRefusal> {
    let end = offset.checked_add(8).ok_or(CarrierRefusal::Malformed)?;
    let field = bytes.get(offset..end).ok_or(CarrierRefusal::Malformed)?;
    Ok(u64::from_le_bytes(
        field.try_into().expect("an 8-byte slice"),
    ))
}

/// The parsed body of a document, before any semantic binding. Holds the
/// fields exactly as submitted; nothing here has been trusted yet.
#[derive(Clone, Debug, Eq, PartialEq)]
struct ParsedBody {
    direction: Direction,
    descriptor_digest: String,
    endpoint_identity_digest: String,
    instance_identity_digest: String,
    leaf_inventory_digest: String,
    leaves: Vec<ReferenceLeaf>,
}

impl ParsedBody {
    /// Reassemble the exact preimage the trailing digest is computed over,
    /// from what was parsed rather than from the submitted bytes, so a
    /// noncanonical encoding of the same logical value cannot reproduce a
    /// matching digest.
    fn preimage(&self) -> Vec<u8> {
        let mut preimage = Vec::new();
        push_field(&mut preimage, REFERENCE_CARRIER_SCHEMA.as_bytes());
        push_field(&mut preimage, direction_text(self.direction).as_bytes());
        push_field(&mut preimage, self.descriptor_digest.as_bytes());
        push_field(&mut preimage, self.endpoint_identity_digest.as_bytes());
        push_field(&mut preimage, self.instance_identity_digest.as_bytes());
        push_field(&mut preimage, self.leaf_inventory_digest.as_bytes());
        preimage.extend_from_slice(&(self.leaves.len() as u64).to_le_bytes());
        let total: u64 = self
            .leaves
            .iter()
            .map(|leaf| leaf.payload.len() as u64)
            .sum();
        preimage.extend_from_slice(&total.to_le_bytes());
        for leaf in &self.leaves {
            push_field(&mut preimage, leaf.path.as_bytes());
            // The single admitted `LeafKind::Bytes` variant tag. A document
            // that carries any other tag is refused at parse time; this
            // constant is never taken from the wire.
            preimage.push(0);
            push_field(&mut preimage, &leaf.payload);
        }
        preimage
    }
}

fn direction_text(direction: Direction) -> &'static str {
    match direction {
        Direction::Input => "input",
        Direction::Result => "result",
    }
}

fn direction_from_text(text: &str) -> Option<Direction> {
    Some(match text {
        "input" => Direction::Input,
        "result" => Direction::Result,
        _ => return None,
    })
}

/// Parse `bytes` structurally. Every bound is checked before the allocation
/// it governs, and the trailing digest is independently recomputed over the
/// reassembled preimage before the parsed value is returned.
fn parse(bytes: &[u8]) -> Result<ParsedBody, CarrierRefusal> {
    if bytes.len() as u64 > REFERENCE_MAX_WIRE_BYTES {
        return Err(CarrierRefusal::Capacity);
    }

    let mut offset = 0usize;
    let schema = read_text(bytes, &mut offset, REFERENCE_MAX_FIELD_BYTES)?;
    if schema != REFERENCE_CARRIER_SCHEMA {
        return Err(CarrierRefusal::Malformed);
    }
    let direction = direction_from_text(read_text(bytes, &mut offset, REFERENCE_MAX_FIELD_BYTES)?)
        .ok_or(CarrierRefusal::Malformed)?;
    let descriptor_digest = read_text(bytes, &mut offset, REFERENCE_MAX_FIELD_BYTES)?.to_owned();
    let endpoint_identity_digest =
        read_text(bytes, &mut offset, REFERENCE_MAX_FIELD_BYTES)?.to_owned();
    let instance_identity_digest =
        read_text(bytes, &mut offset, REFERENCE_MAX_FIELD_BYTES)?.to_owned();
    let leaf_inventory_digest =
        read_text(bytes, &mut offset, REFERENCE_MAX_FIELD_BYTES)?.to_owned();

    let leaf_count = read_u64(bytes, &mut offset)?;
    if leaf_count > REFERENCE_MAX_OWNED_LEAVES {
        return Err(CarrierRefusal::Capacity);
    }
    let declared_total = read_u64(bytes, &mut offset)?;
    if declared_total > REFERENCE_MAX_TOTAL_PAYLOAD_BYTES {
        return Err(CarrierRefusal::Capacity);
    }

    // `leaf_count` is already bounded at 256 above, so this reservation can
    // never be driven past the frozen bound by a hostile claim.
    let mut leaves: Vec<ReferenceLeaf> = Vec::with_capacity(leaf_count as usize);
    let mut running_total: u64 = 0;
    for _ in 0..leaf_count {
        let path = read_text(bytes, &mut offset, REFERENCE_MAX_FIELD_BYTES)?.to_owned();
        if leaves.iter().any(|leaf| leaf.path == path) {
            return Err(CarrierRefusal::Malformed);
        }
        let tag = *bytes.get(offset).ok_or(CarrierRefusal::Malformed)?;
        offset += 1;
        if tag != 0 {
            return Err(CarrierRefusal::Malformed);
        }
        // Bound the declared payload length before the read that would act
        // on it: an over-bound claim is a capacity refusal, never a large
        // read followed by a length complaint.
        if peek_u64(bytes, offset)? > REFERENCE_MAX_BYTES_PER_LEAF {
            return Err(CarrierRefusal::Capacity);
        }
        let payload = read_field(bytes, &mut offset, REFERENCE_MAX_BYTES_PER_LEAF)?;
        running_total = running_total
            .checked_add(payload.len() as u64)
            .ok_or(CarrierRefusal::Capacity)?;
        if running_total > REFERENCE_MAX_TOTAL_PAYLOAD_BYTES {
            return Err(CarrierRefusal::Capacity);
        }
        leaves.push(ReferenceLeaf {
            path,
            payload: payload.to_vec(),
        });
    }

    if running_total != declared_total {
        return Err(CarrierRefusal::Malformed);
    }

    let submitted_facts_digest =
        read_text(bytes, &mut offset, REFERENCE_MAX_FIELD_BYTES)?.to_owned();
    if offset != bytes.len() {
        return Err(CarrierRefusal::Malformed);
    }

    let body = ParsedBody {
        direction,
        descriptor_digest,
        endpoint_identity_digest,
        instance_identity_digest,
        leaf_inventory_digest,
        leaves,
    };
    if domain_digest(FRAME_DOMAIN, &body.preimage()) != submitted_facts_digest {
        return Err(CarrierRefusal::ReplayMismatch);
    }
    Ok(body)
}

/// Parse an untrusted document and replay it against a trusted plan.
///
/// Structural admission and semantic binding are deliberately separate
/// phases: a document that merely decodes is never confused with one that
/// belongs to the expected descriptor, endpoint, instance, direction and
/// leaf inventory. A reminted, internally self-consistent forgery clears the
/// first phase and is refused by the second.
pub fn decode_and_bind(
    bytes: &[u8],
    plan: &ReferencePlan,
) -> Result<Vec<ReferenceLeaf>, CarrierRefusal> {
    let body = parse(bytes)?;

    if body.direction != plan.direction {
        return Err(CarrierRefusal::ReplayMismatch);
    }
    if body.descriptor_digest != plan.descriptor_digest {
        return Err(CarrierRefusal::ReplayMismatch);
    }
    // Recomputed from the trusted `export_id`, never taken from the wire.
    if body.endpoint_identity_digest != endpoint_identity_digest(&plan.export_id) {
        return Err(CarrierRefusal::ReplayMismatch);
    }
    if body.instance_identity_digest != plan.instance_identity_digest {
        return Err(CarrierRefusal::ReplayMismatch);
    }
    // Recomputed from the trusted canonical path list, never taken from the
    // wire — so a forged inventory digest that happens to match the forged
    // paths is still refused.
    if body.leaf_inventory_digest != leaf_inventory_digest(&plan.leaf_paths) {
        return Err(CarrierRefusal::ReplayMismatch);
    }
    let submitted: Vec<&str> = body.leaves.iter().map(|leaf| leaf.path.as_str()).collect();
    let expected: Vec<&str> = plan.leaf_paths.iter().map(String::as_str).collect();
    if submitted != expected {
        return Err(CarrierRefusal::ReplayMismatch);
    }
    Ok(body.leaves)
}

/// Encode a canonical, self-digested document for `plan` from `payloads`,
/// in canonical leaf order. Used to build the corpus baseline and its
/// positive controls; hostile documents are produced by recorded mutation of
/// this output.
///
/// Returns `None` when `payloads` does not have exactly one entry per
/// canonical leaf path, so a fixture cannot silently encode a shape the plan
/// never described.
pub fn encode_canonical(plan: &ReferencePlan, payloads: &[Vec<u8>]) -> Option<Vec<u8>> {
    if payloads.len() != plan.leaf_paths.len() {
        return None;
    }
    let leaves: Vec<ReferenceLeaf> = plan
        .leaf_paths
        .iter()
        .zip(payloads)
        .map(|(path, payload)| ReferenceLeaf {
            path: path.clone(),
            payload: payload.clone(),
        })
        .collect();
    let body = ParsedBody {
        direction: plan.direction,
        descriptor_digest: plan.descriptor_digest.clone(),
        endpoint_identity_digest: plan.endpoint_identity_digest.clone(),
        instance_identity_digest: plan.instance_identity_digest.clone(),
        leaf_inventory_digest: plan.leaf_inventory_digest.clone(),
        leaves,
    };
    let mut bytes = body.preimage();
    push_field(
        &mut bytes,
        domain_digest(FRAME_DOMAIN, &body.preimage()).as_bytes(),
    );
    Some(bytes)
}

/// Recompute and rewrite a document's trailing `carrier_facts_digest` so
/// that the document becomes internally self-consistent again after its
/// body was mutated.
///
/// This is the forgery primitive the corpus needs: it manufactures exactly
/// the document a digest-only reader would accept. It is deliberately
/// exposed so the corpus can prove that recomputing the *trusted roots*,
/// not merely checking the embedded digest, is what refuses it. Returns
/// `None` when the mutated body does not parse structurally, because there
/// is then no body to remint over.
pub fn remint_facts_digest(bytes: &[u8]) -> Option<Vec<u8>> {
    // Deliberately structural only: the whole point of this primitive is to
    // repair a document whose trailing digest no longer matches, and several
    // corpus cases also violate a check `parse` performs before it (a
    // duplicate leaf path, for instance). Reusing `parse` here would refuse
    // exactly the documents that most need reminting.
    let body = reparse_ignoring_digest(bytes)?;
    let preimage = body.preimage();
    let mut candidate = bytes.to_vec();
    candidate.truncate(preimage.len());
    push_field(
        &mut candidate,
        domain_digest(FRAME_DOMAIN, &preimage).as_bytes(),
    );
    Some(candidate)
}

/// Parse a document whose trailing digest is known not to match, by
/// substituting a correct digest first. Only ever used by
/// [`remint_facts_digest`].
fn reparse_ignoring_digest(bytes: &[u8]) -> Option<ParsedBody> {
    // The trailing field is the last length-framed field; find its start by
    // walking backwards over its own length header.
    if bytes.len() < 8 {
        return None;
    }
    let mut offset = 0usize;
    // Re-walk the body exactly as `parse` does, stopping before the digest.
    let schema = read_text(bytes, &mut offset, REFERENCE_MAX_FIELD_BYTES).ok()?;
    if schema != REFERENCE_CARRIER_SCHEMA {
        return None;
    }
    let direction =
        direction_from_text(read_text(bytes, &mut offset, REFERENCE_MAX_FIELD_BYTES).ok()?)?;
    let descriptor_digest = read_text(bytes, &mut offset, REFERENCE_MAX_FIELD_BYTES)
        .ok()?
        .to_owned();
    let endpoint_identity_digest = read_text(bytes, &mut offset, REFERENCE_MAX_FIELD_BYTES)
        .ok()?
        .to_owned();
    let instance_identity_digest = read_text(bytes, &mut offset, REFERENCE_MAX_FIELD_BYTES)
        .ok()?
        .to_owned();
    let leaf_inventory_digest = read_text(bytes, &mut offset, REFERENCE_MAX_FIELD_BYTES)
        .ok()?
        .to_owned();
    let leaf_count = read_u64(bytes, &mut offset).ok()?;
    if leaf_count > REFERENCE_MAX_OWNED_LEAVES {
        return None;
    }
    let _declared_total = read_u64(bytes, &mut offset).ok()?;
    let mut leaves = Vec::with_capacity(leaf_count as usize);
    for _ in 0..leaf_count {
        let path = read_text(bytes, &mut offset, REFERENCE_MAX_FIELD_BYTES)
            .ok()?
            .to_owned();
        let tag = *bytes.get(offset)?;
        offset += 1;
        if tag != 0 {
            return None;
        }
        let payload = read_field(bytes, &mut offset, REFERENCE_MAX_BYTES_PER_LEAF).ok()?;
        leaves.push(ReferenceLeaf {
            path,
            payload: payload.to_vec(),
        });
    }
    Some(ParsedBody {
        direction,
        descriptor_digest,
        endpoint_identity_digest,
        instance_identity_digest,
        leaf_inventory_digest,
        leaves,
    })
}

/// Cross-check helper: this module's bound literals against the frozen
/// profile. Kept out of `#[cfg(test)]` so an integration harness can assert
/// the same identity.
pub fn reference_bounds_match_boundary_profile() -> bool {
    REFERENCE_MAX_OWNED_LEAVES == MAX_OWNED_LEAVES_PER_INSTANCE as u64
        && REFERENCE_MAX_BYTES_PER_LEAF == MAX_BYTES_PER_LEAF as u64
        && REFERENCE_MAX_TOTAL_PAYLOAD_BYTES == MAX_TOTAL_PAYLOAD_BYTES as u64
        && REFERENCE_CARRIER_SCHEMA == CARRIER_SCHEMA
}

#[cfg(test)]
mod tests;
